### ISSUE TITLE
It says my client is outdated, but the opposite is true. 

### ISSUE THREAD

**Issue by willotheblessed** [iTXTech/Genisys#1505] opened 2016-07-21 18:06 UTC
#### Issue description
I am trying to sign in a 0.15.3 client on the 0.15.0 Alpha server. It says my client is outdated, but the opposite is true. This message is confusing, not sure how to fix. The server message should be more helpful.

#### Steps to reproduce the issue
Download latest version (https://gitlab.com/itxtech/genisys/pipelines/3757015)
Update to latest Minecraft: PE (0.15.3)
Attempt to sign into game.

#### OS and versions
* Genisys: git-e166843
* PHP: 7,0
* Server OS: Windows 10
* Game version: v0.15.0 alpha (protocol version 81)

#### Crashdump, backtrace, memory dumps, plugins list or other files
016-07-21 [09:14:29] [Server thread/INFO]: [/192.168.1.19:19132] logged out due to Your MCPE client is outdated!

**Comment by dktapps** [comment] 2016-07-21 18:12
Cannot reproduce, and that message does not match anything that Genisys would output in the case of a client _actually_ being outdated.

**Comment by ZedCee** [comment] 2016-07-21 18:16
0.15.3 literally just came out, is not available for all platforms and thus not officially supported yet.  Developers on our team aren't experiencing the same issue and until 0.15.3s widespread release this cannot not be corrected.

Following that much;  Genisys-Win10 is heavily in beta and is also not officially supported until it is ready to be merged with the master release.  Thus we cannot handle those issues yet.

**Closed by ZedCee** 2016-07-21 18:16 UTC

**Comment by dktapps** [comment] 2016-07-21 18:19
This looks like a plugin problem to me. There is nothing in Genisys which would output such a message. Genisys always says either "Outdated client!" or "Outdated server!". Nothing more, nothing less.

**Comment by SleepSpace9** [comment] 2016-07-22 21:28
Maybe you have the CustomAlerts Plugin which is known for those problems. If so try to disable it and test again.
