### ISSUE TITLE
Void and kill doesaint work

### ISSUE THREAD

**Issue by YoungRichNigger9** [iTXTech/Genisys#1196] opened 2016-06-17 16:42 UTC
When one of my players does use /kill it doesaint do none and also in parkour when you fall in in void you well be teleport bck up

**Comment by dktapps** [comment] 2016-06-17 17:27
Cannot reproduce, and you haven't followed the issue template. Most likely plugin issues. Closing.

**Closed by dktapps** 2016-06-17 17:27 UTC
