### ISSUE TITLE
Floating Text in all worlds

### ISSUE THREAD

**Issue by erkam2002** [iTXTech/Genisys#1986] opened 2016-09-24 16:55 UTC
#### Issue description

If i made a plugin with floating text in 1 worlds than its in all worlds and all server with synapse but i havent this plugin on all servers...
#### OS and versions

- Genisys: 147
- PHP: 7.0.11
- Server OS: Ubuntu 14.,0
- Game version: 0.15.9
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by MattWAnderson** [comment] 2016-09-26 00:07
This does not have enough information.

**Comment by erkam2002** [comment] 2016-09-26 15:56
Now!

**Comment by MattWAnderson** [comment] 2016-09-26 22:28
This is more than likely due to the fact the particle is being pushed to the client in a x y z position and the client holds that particle regardless of world or map type. You would need to modify a plugin to remove the particles from a client when they change worlds.

**Comment by erkam2002** [comment] 2016-09-27 14:30
Ok..

**Comment by dktapps** [comment] 2016-09-27 14:32
Don't close it until the issue is resolved. @MattWAnderson 's suggestion is just a workaround, not a fix.

**Comment by jjplaying** [comment] 2016-09-27 17:10
In my plugin, I'm just getting the spawned particle (so you need an array of all spawned particles of a player), setting it to invisible, and sending it to the client again when the player quits. As far as I know, that's the only way to do it.

You can't really fix it because you can't despawn an already spawned particle, but it's possible to implement this workaround into Genisys (currently working on it).

**Comment by dktapps** [comment] 2016-09-27 17:14
This problem results because FloatingTextParticle is actually an entity, and the server doesn't keep track of it. FloatingTextParticle is very hacky.

**Comment by jjplaying** [comment] 2016-09-27 17:24
So it's not possible to track it as an entity?

**Comment by dktapps** [comment] 2016-09-27 17:54
@jjplaying I didn't say it wasn't possible, only that the server should do it and doesn't.

**Comment by XFuryMCPE** [comment] 2016-09-30 21:27
Well, Single Player doesn't allow multiworld, so this wouldn't work. You'd have to find each FloatingTextParticle in the previous work and send a RemoveEntityPacket to the player, which would be kinda hard, since their entity ids aren't logged anywhere. This happens upon transferring with Nemisys aswell, but I use specific entity ids and despawn them using those

**Comment by sero583** [comment] 2016-10-07 18:14
@XFuryMCPE Ehmm... but it would work when he would do a array like array("Steve" => FTPObject); and then just, remove it.
Last once I tried that method, was in so 0.14.X, so I think it would still work, but I'm not sure too.

**Comment by XFuryMCPE** [comment] 2016-10-07 18:16
Or we could actually register FloatingTextParticles as entities, so they
stay on one world

**Comment by sero583** [comment] 2016-10-07 18:18
@XFuryMCPE Isn't that just a harder way to do it, since it exists easier ways, to do it?
But your idea is nice too, the Server handles then it, itself.

**Comment by Misteboss** [comment] 2016-10-09 15:50
@XFuryMCPE How do you remove FloatingText ? Code ?

**Comment by XFuryMCPE** [comment] 2016-10-09 16:56
RemoveEntityPacket

**Comment by Misteboss** [comment] 2016-10-09 17:56
Yes but how can i define the entity packet ?

**Comment by jjplaying** [comment] 2016-10-09 18:04
Got it working as entity now, spawn and despawn works, I'll fix some smaller bugs (it's getting empty but keeps visible on server restart) and test it, then do a PR: https://github.com/jjplaying/Genisys/tree/floating-as-entity

**Comment by Misteboss** [comment] 2016-10-09 18:12
How can i despawn it

**Comment by jjplaying** [comment] 2016-10-09 18:14
When it's ready and working, you can spawn and despawn FloatingTexts like Entities, that's my test code:

```php
public function onPlayerJoin(PlayerJoinEvent $event) {
        $player = $event->getPlayer();

        $x = $player->getX();
        $y = $player->getY();
        $z = $player->getZ();

        $level = $player->getLevel();
        $chunk = $level->getChunk($x >> 4, $z >> 4);

        $nbt = new CompoundTag("", array(
            "Pos" => new ListTag("Pos", array(
                new DoubleTag("", $x),
                new DoubleTag("", $y),
                new DoubleTag("", $z)
            )),
            "Motion" => new ListTag("Motion", array(
                new DoubleTag("", 0),
                new DoubleTag("", 0),
                new DoubleTag("", 0)
            )),
            "Rotation" => new ListTag("Rotation", array(
                new FloatTag("", lcg_value() * 360),
                new FloatTag("", 0)
            ))
        ));

        $entity = Entity::createEntity("FloatingText", $chunk, $nbt);

        if($entity instanceof FloatingText) {
            echo "LOS";

            $entity->setTitle("Hallo");
            $entity->setText("Das ist ein Test.");

            $entity->spawnToAll();
        }
    }

    public function onPlayerChat(PlayerChatEvent $event) {
        $player = $event->getPlayer();

        foreach($player->getLevel()->getEntities() as $entity) {
            if($entity instanceof FloatingText) {
                $entity->despawnFromAll();
            }
        }
    }
```

**Comment by jjplaying** [comment] 2016-10-09 18:18
I did some tests and it's working great, spawn and despawn it like an entity, and it despawns on world change, so I'll create a PR now.

**Comment by Misteboss** [comment] 2016-10-09 19:14
Ok thanks @jjplaying did that work without your version of Genisys ?

**Comment by jjplaying** [comment] 2016-10-09 19:53
No, you need to wait until the PR is finished, then it's in Genisys.

**Comment by legoboy0215** [comment] 2016-10-10 01:49
I think a way is to make the randomly generated entity ID for the floating text particle to public, or even write a getter. 

My current hack:
```
/TODO: Remove FloatingTextParticle removal hack
            $rp = new \ReflectionProperty(FloatingTextParticle::class, 'entityId');
            $rp->setAccessible(true);

            $pk = new RemoveEntityPacket;
            $pk->eid = $rp->getValue($textParticleObject);
            $player->dataPacket($pk);
```

**Comment by jjplaying** [comment] 2016-10-10 05:09
Yeah, the original issue wouldn't be solved with that way, you still need to despawn them manually.

**Closed** 2017-01-21 18:06 UTC
Labels: bug
