### ISSUE TITLE
addWindow() broken

### ISSUE THREAD

**Issue by GenisysFTW** [iTXTech/Genisys#1639] opened 2016-08-11 23:24 UTC
#### Issue description
addWindow() is still not working. When I'm at spawn (near X: 128, Z: 128), addwWindow() doesn't work. But when I to myself to
X: 1000
Z: 1000
addWindow() suddenly starts working.

#### Steps to reproduce the issue
1. Be at the initial spawn of your world (128,~,128)
2. Spawn a chest block. ($level->setBlock())
3. Spawn a chest tile. ($nbt..., Tile::createTile())
4. Add window to yourself. ($player->addWindow($tileChest->getInventory()))

#### OS and versions
* Genisys: c19e8509
* PHP: 7.0.8 and 7.0.9
* Server OS: Ubuntu 14.04 and Ubuntu 16.04
* Game version: 0.15.4 and 0.15.6

```
```

**Comment by GenisysFTW** [comment] 2016-08-11 23:26
P.S: This works on ClearSky for I don't know what reason. But who is ever going to use ClearSky?

**Comment by diamond-gold** [comment] 2016-08-12 03:00
How far are you from the chest when you addwindow?

**Comment by ishitatsuyuki** [comment] 2016-08-12 03:52
As @diamond-gold say, PE has a distance check when you open the window.

**Comment by Muqsit** [comment] 2016-08-12 05:18
Confirmed, the bug exists ._.

**Comment by GenisysFTW** [comment] 2016-08-12 05:20
@ishitatsuyuki @diamond-gold @muqsit no. I spawned the chest right on my legs. So I was no distance away from the chest. But still addWindow didn't work.

**Comment by GenisysFTW** [comment] 2016-08-12 06:04
@ishitatsuyuki @diamond-gold See. Download my plugin:
https://github.com/GenisysFTW/addWindow

Do /addwindow
If it works, go it down and try there.
If it does not work, tp to 1000,~,1000 and try there.

**Comment by diamond-gold** [comment] 2016-08-17 15:42
It seems that when x is negative it will try to open the chest that is at x +1 and when z is negative it will open chest at z + 1, when both x and z are positive, it opens normally

**Comment by ishitatsuyuki** [comment] 2016-08-17 15:47
Thank you for the details. It seems it's improperly converted if it's negative. (int cast vs floor())

**Comment by dktapps** [comment] 2016-08-17 15:53
That's interesting. I'll test this. Hardly surprising though. So anything in negative coordinates will fail?

**Comment by dktapps** [comment] 2016-08-17 21:13
Still cannot reproduce. \*sigh\*

**Comment by GenisysFTW** [comment] 2016-09-04 01:47
@dktapps you sure? What OS are you on?

**Comment by Muqsit** [comment] 2016-09-04 08:49
@GenisysFTW In your plugin, line 29:
Use this instead:
```
$x = $p->x();$y = $p->y();$z = $p->z();$level = $p->getLevel();

```

There's an issue with setting block at $p->getX()... etc. but $p->x...etc works perfectly.

**Comment by Muqsit** [comment] 2016-09-05 09:12
I think we can close this now? This is the correct way of spawning chests + addWindow()...
```php
public function sendChestInventory(Player $player){
  $block = Block::get(54,15);
  $player->getLevel()->setBlock(new Vector3($player->x, $player->y - 2, $player->z), $block, true, true);
  $nbt = new CompoundTag("", [
    new ListTag("Items", []),
    new StringTag("id", Tile::CHEST),
    new IntTag("x", floor($player->x)),
    new IntTag("y", floor($player->y) - 2),
    new IntTag("z", floor($player->z))
  ]);
  $nbt->Items->setTagType(NBT::TAG_Compound);
  $tile = Tile::createTile("Chest", $player->getLevel()->getChunk($player->getX() >> 4, $player->getZ() >> 4), $nbt);
  $player->addWindow($tile->getInventory());
}
```
^
This worked every time for me, even at negative coordinates.

**Comment by dktapps** [comment] 2016-09-05 10:20
Windows, and never able to reproduce this. I think it may be a better idea to use getFloorX() or floor($player->x).

**Comment by GenisysFTW** [comment] 2016-09-05 19:46
@Muqsit @dktapps thank you both soo much. addWindow() now running smoother than ever! :100:

**Closed** 2016-09-09 09:26 UTC
Labels: bug
