### ISSUE TITLE
Keep Inventory and Experience problem

### ISSUE THREAD

**Issue by Adam1609** [iTXTech/Genisys#2116] opened 2016-10-23 09:02 UTC
#### Issue description
 Keep Inventory and Keep Experience don't work, I tried dying and conclusion all items were disappeared, after I left the server and join again it brought back my exp and my items

#### Steps to reproduce the issue

1, Execute /kill or let somebody kill you
2, See the missing item and experiences

#### OS and versions

* Genisys: Kyrios_c463255
* PHP: 7.0.5
* Server OS: Windows Server 2012
* Game version: 0.15 universal

#### Crashdump, backtrace, memory dumps, plugins list or other files

Alias 1.2.0 by ZacHack for API(s) 1.12.0
AlwaysSpawn 2.2.2 by Philip Shilling for API(s) 1.12.0
Broadcaster 1.16 by EvolSoft for API(s) 1.12.0
CommandTracker 1.1 by Scott Handley for API(s) 1.10.0
CoreProtect 0.0.2 by ImagicalGamer for API(s) 1.0.0, 2.0.0, 3.0.0
DevTools 1.1-iTX by PocketMine Team & iTX Technologies LLC for API(s) 2.0.0
EconomyAPI 2.0.9 by onebone for API(s) 2.0.0
EconomyJob 2.0.4 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1, 1.12.0, 1.13.0, 2.0.0
EconomySell 2.0.7 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1, 1.12.0, 1.13.0, 2.0.0
EconomyShop 2.0.7 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1, 1.12.0, 1.13.0, 2.0.0
EmptyWorld 1.1.0 by aliuly for API(s) 2.0.0
FuckingSpam 0.1 by BalAnce for API(s) 1.12.0
GMChecker 0.2 by  for API(s) 1.12.0
ItemCasePE 1.0.8 by aliuly for API(s) 1.10.0, 1.13.0
LaunchPads 1.0.0 by MCPEPIG for API(s) 1.0.0
ManyWorlds 2.1.0 by aliuly for API(s) 2.0.0
MSpawns 1.5 by EvolSoft for API(s) 1.11.0
NetherChests 1.1.1 by aliuly for API(s) 1.12.0
NoDrops 1 by Yupai for API(s) 2.0.0
PmChair 1.2 by maru for API(s) 1.12.0, 1.13.0, 2.0.0
PrizeWin 1.0.6 by LilCrispy2o9/Angelo Vidrio for API(s) 1.10.0
PurePerms 1.3.7 by 64FF00 & ProjectInfinity for API(s) 1.13.0, 2.0.0
Sell 2 by Muqsit for API(s) 2.0.0
SimpleAuth 1.7.2 by PocketMine Team, shoghicp for API(s) 2.0.0
SkinChanger 1.2.3 by SalmonDE, Aericio, KairusDarkSeeker for API(s) 2.0.0
ZMusicBox 2.5.0 by Zzm for API(s) 1.0.0
TapToDo 2.2.1 by Falk for API(s) 1.0.0
VAC 3.0.1 by DarkWav for API(s) 2.0.0, 1.0.0
VoteReward 3.0.2 by LDX for API(s) 1.12.0, 2.0.0
WorldEdit 1.0.2 by  for API(s) 1.13.0
WorldProtect 2.2.0 by aliuly for API(s) 1.10.0, 1.12.0
SimpleAuthHelper 2.0.4 by aliuly for API(s) 1.12.0
PureChat 1.4.0 by 64FF00 for API(s) 1.13.0, 2.0.0
CustomAlerts 1.6 by EvolSoft for API(s) 1.12.0
EssentialsPE 2.0.0 by LegendsOfMCPE Team for API(s) 2.0.0
FactionsPro 1.3.2 by Array for API(s) 1.14.0, 2.0.0
FixMUALagg 0.1 by Adam1609 credit to PEMapModder for API(s) 2.0.0
LevelSystem 1.0.0 by FAMIMA for API(s) 1.0.0, 2.0.0
RedMTag 1 by Skullex for API(s) 1.13.1, 2.0.0, 1.0.0, 1.14.0
REDSmelt 1.0 by SavionLegendZzz for API(s) 1.12.0
MiniBosses 1.0.0 by ace for API(s) 1.0.0
REDFix 1.0.0 by ace aka wolfdale for API(s) 1.2.0
REDCrit 1 by Adam1609 credit to Ad5001 for API(s) 2.0.0
REDFeed 1.0BETA by  for API(s) 1.14.0, 2.0.0
REDLagg 0.1 by Adam1609 credit to Sergey_Dertan for API(s) 1.8.0
REDSprint 1.0.0 by OpenBuild Dev Team (Efra1in16) for API(s) 1.12.0
REDVIP 1.0.0 by MyL Team for API(s) 1.12.0
REDFarms 0.0.1 by GlxTeam for API(s) 2.0.0
RedFB 1.0.1 by Adam1609 for API(s) 2.0.0
REDNoBreak 0.1 by Adam1609 for API(s) 2.0.0
RED 0.1 by Adam1609 for API(s) 2.0.0
PocketRPG 0.3.0 by Sandertv for API(s) 2.0.0, 1.13.0
Slapper 1.2.9.7 by jojoe77777 for API(s) 2.0.0
TradeCraft 0.2 by Jarest (translate and fixable by Adam1609) for API(s) 2.0.0
MyPlot 1 by Wies and Exxarion for API(s) 2.0.0

```
```

**Comment by ishitatsuyuki** [comment] 2016-10-23 09:06
You have such a large amount of plugins, remove and try again.

**Comment by dktapps** [comment] 2016-10-23 09:17
Cannot reproduce with a clean server, closing.

**Closed by dktapps** 2016-10-23 09:17 UTC
