### ISSUE TITLE
All players creative inventory is blank

### ISSUE THREAD

**Issue by Lucario2** [iTXTech/Genisys#202] opened 2016-01-31 13:50 UTC

**Comment by PocketKiller** [comment] 2016-01-31 13:53
sure? delete all plugins and test.

**Comment by Lucario2** [comment] 2016-01-31 13:59
I did.

**Comment by Lucario2** [comment] 2016-01-31 13:59
YOU THINK I DIDN'T TRY THAT? That's so noob.

**Comment by MilkoIvanov** [comment] 2016-01-31 18:11
The problem is that when you are on creative, and logout then login again your creative bar is blank and you have to change your gamemode back to survival then to creative and everything is normal

**Comment by Lucario2** [comment] 2016-01-31 18:14
Yeah but I need for the players to vote

**Comment by Lucario2** [comment] 2016-01-31 18:14
I need their votes

**Comment by Efforto** [comment] 2016-02-02 10:16
BLANK!?Try to change gamemode , from Survival mode to Creative mode
this may happen sometimes

**Comment by PeratX** [comment] 2016-02-02 12:24
Fixed in build 3

**Closed** 2016-02-02 13:08 UTC
