### ISSUE TITLE
Item frame item duplication

### ISSUE THREAD

**Issue by andris155** [iTXTech/Genisys#2321] opened 2017-01-20 13:25 UTC
#### Issue description

Genisys 1.0.0 infinity items protected item frame (iprotector)

#### Steps to reproduce the issue

touch protected item frames

#### OS and versions

* Genisys: https://github.com/iTXTech/Genisys/tree/b45dc8fb06584cc7970318eaee20b6f510c94799
* PHP: 7.0.14
* Server OS: Ubuntu 16.04.1
* Game version: Android

#### Crashdump, backtrace, memory dumps, plugins list or other files

https://www.youtube.com/watch?v=kRpnnA_Guxk

**Comment by isoz** [comment] 2017-01-20 13:52
I mean, duplicating...

**Comment by JackNoordhuis** [comment] 2017-01-21 05:09
I cannot reproduce this. I will be closing this issue due to the fact that it is not possible to reproduce this on an unmodified version of Genisys from the mcpe-1.0 branch. There is no way to stop items dropping from item frames so I don't see how you could've reproduced this without a plugin doing so. If you can provide in-depth steps on how to reproduce this on an unmodified version of Genisys I will reopen his issue.

**Closed by JackNoordhuis** 2017-01-21 05:09 UTC
