### ISSUE TITLE
addWindow / chests broken

### ISSUE THREAD

**Issue by robske110** [iTXTech/Genisys#1594] opened 2016-08-03 13:33 UTC
#### Issue description
I cannot open chests neither open inventories using the addWindow method

#### Steps to reproduce the issue
Try to open a chest->no inventory or whatsoever appears

#### OS and versions

* Genisys: https://github.com/iTXTech/Genisys/commit/45f2ae0840c270cb22c4e9af43abe550c4112593
* PHP: 7.0.6
* Server OS: MacOSX
* Game version: 0.15.4

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Muqsit** [comment] 2016-08-03 13:49
Yeah, having the same issue since 0.15. We will investigate...

**Comment by dktapps** [comment] 2016-08-03 14:02
I sometimes get this on the Win10 branch. I haven't figured out what's causing it yet.

**Comment by dktapps** [comment] 2016-08-03 14:13
Noting that this happens _occasionally_ for me.

**Comment by robske110** [comment] 2016-08-03 15:00
Noting that this happens always for me on the master branch
Btw CS has no problems at all

**Comment by gaoyichuan** [comment] 2016-08-04 01:48
@robske110 Also CS has no feature at all

**Comment by robske110** [comment] 2016-08-04 08:17
Idc, i just pointed out that this is 100% Genisys's fault. We didn't change inventory for 0.15 in CS

**Comment by dktapps** [comment] 2016-08-04 09:30
@robske110 Nothing has changed inventory-wise whatsoever for 0.15 here either. I suggest you get your facts straight.

**Comment by Muqsit** [comment] 2016-08-04 10:23
Well, thanks for the hint @robske110 !

**Comment by robske110** [comment] 2016-08-04 10:28
Strange, I'll look at CS if we did anything inventory related in CS. And i'm just trying tonpoint out that this issue is a server side issue. If i find sth, I'll comment here.

**Comment by Muqsit** [comment] 2016-08-06 06:54
This issue has been fixed over here https://github.com/iTXTech/Genisys/pull/1605
Confirmed, and positive reviews too! (Lowkey want someone to +1 that pull).

**Comment by dktapps** [comment] 2016-08-06 10:00
@Muqsit I find it unlikely that that's the true solution.

**Comment by dktapps** [comment] 2016-08-08 10:51
This was fixed in https://github.com/iTXTech/Genisys/commit/1890dac91da327bd1bf5c5b86d41ae0b27a26328
Closing.

**Closed by dktapps** 2016-08-08 10:51 UTC
Labels: bug
