### ISSUE TITLE
Drop

### ISSUE THREAD

**Issue by SuperAlecs** [iTXTech/Genisys#516] opened 2016-03-06 13:41 UTC
If players have full inventory and take drops it drop other items! please fix it

**Comment by fycarman** [comment] 2016-03-07 06:28
I can confirm this issue. How to reproduce: fill your inventory,then take 1 or more items from the ground,it will drop items in your inventory and pick up items on ground

**Comment by ishitatsuyuki** [comment] 2016-03-07 07:47
Could not reproduce. Are you running master?

**Comment by astersx** [comment] 2016-03-07 10:50
It happen to me too :)

**Comment by ishitatsuyuki** [comment] 2016-03-07 10:51
Cannot confirm. Please provide the git hash.

**Comment by MineBuilderFR** [comment] 2016-03-07 23:22
I confirm This issue and i have This bug

**Comment by ishitatsuyuki** [comment] 2016-03-08 02:53
Closing for insufficient information.

**Closed by ishitatsuyuki** 2016-03-08 02:53 UTC
Labels: invalid, not confirmed, possibly fixed
