### ISSUE TITLE
Sometimes on Shutdown

### ISSUE THREAD

**Issue by TheClimbing** [iTXTech/Genisys#2350] opened 2017-02-05 17:04 UTC
#### Issue description
Sometimes when the server is shutting down I get this error.Maybe it's because I have PureEntities and Slapper on my server and the entities are getting too much or I don't know actually.

#### Steps to reproduce the issue
I can't provide any steps because it happens only sometimes .But I see this Error once on 10 server restarts

#### OS and versions

* Genisys:Genisys-1ed05b7 
* PHP:7.0.15
* Server OS:Win7
* Game version: 1.0.0.16

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
[Server thread/CRITICAL]: Error: "Call to a member function getServer() on null" (EXCEPTION) in "/src/pocketmine/entity/Entity" at line 1812
[16:37:54] [Server thread/DEBUG]: #0 (): pocketmine\entity\Entity->__destruct(boolean)
[16:37:54] [Server thread/DEBUG]: #1 /src/pocketmine/Server(2207): gc_collect_cycles(boolean)
[16:37:54] [Server thread/DEBUG]: #2 /src/pocketmine/Server(2257): pocketmine\Server->forceShutdown(boolean)
[16:37:54] [Server thread/DEBUG]: #3 /src/pocketmine/Server(1860): pocketmine\Server->start(boolean)
[16:37:54] [Server thread/DEBUG]: #4 /src/pocketmine/PocketMine(479): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar://C:\Users\TheClimbing\Desktop\Genisys_Unsuportted\Genisys.phar/, string C:\Users\TheClimbing\Desktop\Genisys_Unsuportted\, string C:\Users\TheClimbing\Desktop\Genisys_Unsuportted\plugins\)
[16:37:54] [Server thread/DEBUG]: #5 (1): require_once(string phar://C:/Users/TheClimbing/Desktop/Genisys_Unsuportted/Genisys.phar/src/pocketmine/PocketMine.php)
[16:37:54] [Server thread/EMERGENCY]: Crashed while crashing, killing process
```

**Comment by dktapps** [comment] 2017-02-05 17:11
Duplicate of #2322

**Closed by dktapps** 2017-02-05 17:11 UTC

**Comment by TheClimbing** [comment] 2017-02-05 17:13
Oops sorry...
