### ISSUE TITLE
We cant kill mobs that spawn from monster spawner 

### ISSUE THREAD

**Issue by DurianCube** [iTXTech/Genisys#1438] opened 2016-07-12 16:26 UTC
#### Issue description
When u place a zombie spawner or cow spawner , as always it will spawn the mobs but when it spawned i cant kill them even i has on the mobs AI on the confiq. I has try to kill the mobs on survival and creative gamemode but it does't work

#### Steps to reproduce the issue
placeace a spawner and tape it using any mobs spawn eggs (cow or zombies) and wait until the mobs spawn and try kill them . 

Game versions include Pocket Edition and Windows 10 Edition Beta -->
* Genisys:1.2dev
* PHP: latest
* OS (server):Windows 8

**Comment by dktapps** [comment] 2016-07-12 17:28
1.2dev-what? Please write a Jenkins build number of git hash.

Also, I can't reproduce this on any build.

**Comment by JUSTaMod** [comment] 2016-07-12 22:00
Make sure you DO NOT have slapper installed.

**Comment by PeratX** [comment] 2016-07-12 23:25
Can't reproduce.

**Comment by ZedCee** [comment] 2016-07-12 23:36
Well I can't say I've ever had that issue, but I frequently see differences among the platforms.  A couple releases my iPhone cannot connect, others my girlfriend's android cant, however it is infrequent.

Tested with the Zombie AI 2 and I can say yes they are insane to try and kill as they jump around, but purely killable.  Interestingly enough however, the mob spawn appear to be shooting lasers from it, very rapidly...  You know, the brown leash coloured kind. :stuck_out_tongue_winking_eye: 

I'm about to test Zombie AI 1.  I'll be back with an update of the results.

**Comment by ZedCee** [comment] 2016-07-12 23:45
Cannot reproduce.  
Likely a plugin, try vanilla.
Ensure a good connection, as hits can pass through if on a shotty one or not even connected at all in 0.15.2.

Brown Lasers Update:
Also upon closer inspection, just one really fast spinning leashed mob in a spawner.  Fast enough that anywhere past two blocks and the framerate drops on the animation become evident and it appear to flicker. Seems to cause almost no server lag though.

**Comment by ishitatsuyuki** [comment] 2016-07-13 08:04
Cannot reproduce. No version written. Closing.

**Closed by ishitatsuyuki** 2016-07-13 08:04 UTC
