### ISSUE TITLE
Clients do not see the same weather effects

### ISSUE THREAD

**Issue by dktapps** [iTXTech/Genisys#1472] opened 2016-07-16 18:24 UTC
#### Issue description
Clients do not see the same weather when they are in the same world. The below screenshot shows two players in the same world at the same position, looking in the same direction. (Left is PE on Nox, right is Win10 Edition)

#### Steps to reproduce the issue
Not entirely sure how to reproduce this. Will update if I figure out how.

#### OS and versions

* Genisys: b6b3aeb, 63769e6
* PHP: 7.0.8
* Server OS: Windows 10 Home x64
* Game version: MCPE and MC Win10 (both 0.15.2)

#### Crashdump, backtrace, memory dumps, plugins list or other files
![image](https://cloud.githubusercontent.com/assets/14214667/16896414/d5d4606e-4b8a-11e6-8667-e8d7b0ce18af.png)

**Comment by CubeFromSpace** [comment] 2016-07-16 18:44
You should merge this with issue #1337. Not trying to be rude or spammy.

**Comment by dktapps** [comment] 2016-07-16 18:47
@CubeFromSpace why don't you check what #1337 is about? That concerns the Win10 update. This concerns a Genisys bug which is independent of client type.

**Comment by CubeFromSpace** [comment] 2016-07-16 18:49
Ok. Sorry. That technically was spam then.

**Comment by dktapps** [comment] 2016-07-16 18:50
@CubeFromSpace xD. Apology accepted.

**Comment by ZedCee** [comment] 2016-07-16 19:28
Since 0.15.2 I've noticed a lack of adequate synchronization, there appears to be a problem with the client reconnecting; the time and weather continue to function but out-of-sync with the server.  
I use MCPE iOS and Android, and it can be corrected with a re-login.  This appears to be a **client-side connection issue**, especially evident after backgrounding the application and coming back to the server.  The client does not appear to log back in on the server and the server may not show you disconnected yet, but the client has lost the connection.

The Genisys server for Windows 10 is in testing, so the error could also be related to that.
  _Does this issue occur on the server from the Master branch?  Does it occur when players are on the same platform on a fresh log in?_

**Comment by ZedCee** [comment] 2016-07-16 19:38
@dktapps Sorry I should have read the user. :disappointed: :laughing:   The questions  and testing statement were more for the general pop.  @dktapps Knows all of this.  
I can however confirm the issues with weather and time synchronization.

**Comment by PeratX** [comment] 2016-07-17 06:15
@dktapps What is the weather status in server?

**Comment by dktapps** [comment] 2016-07-17 10:16
@PeratX I'm not sure. I haven't been able to reproduce it since. I think it was rainy.

**Comment by Muqsit** [comment] 2016-07-18 05:46
Wait! So that means you can set a client's weather too!?

**Comment by dktapps** [comment] 2016-07-18 12:43
@Muqsit yep. All you have to do is send the weather change packet to one specific player instead of all of them.

**Comment by ZedCee** [comment] 2016-07-18 15:13
@dktapps It's always rainy when I start my server ironically.  For Android users, it seems to rain all the time unless manually changed, resulting over time in differences in the weather.  _Actually rain is a too frequent, but that's my fault not changing the setting yet._

**Comment by yar2001** [comment] 2016-07-19 12:38
I turn off the weather system, but there is still a layer of snow!
MT

**Comment by GlitchPlayer** [comment] 2016-07-21 10:44
Android too. Players can experience sync problems

**Comment by gaoyichuan** [comment] 2016-07-21 14:58
The snow layer is generated by the client. So the server can't affect it

**Comment by ZedCee** [comment] 2016-07-31 16:32
Closing this off for now; Fixed, test and confirmed by @dktapps as of #1570 
If there any issues the arise again, we'll reopen this.

**Comment by dktapps** [comment] 2016-07-31 16:33
@ZedCee no. Leave it, it will be closed automatically when the PR is merged.

**Comment by ZedCee** [comment] 2016-07-31 16:52
Alright sorry, about that.

**Closed** 2016-08-01 04:06 UTC
