### ISSUE TITLE
"Array" messages

### ISSUE THREAD

**Issue by FaanMaario** [iTXTech/Genisys#1490] opened 2016-07-20 03:46 UTC
#### Issue description

On my server, sometimes a message appears "Array", and I don't know why.
It's never happened before.
#### Steps to reproduce the issue

I don't know

#### OS and versions

* Genisys: 1.2dev-ab35ad31
* PHP: php7
* Server OS: GNU/Linux
* Game version: 0.15.2

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
[05:37:49] [m[37m[Server thread/INFO]: [1m[37mArray[m
```

**Comment by ZedCee** [comment] 2016-07-20 05:06
Do you have any plugins installed?

Very frequently there are issues caused by plugins(outdated or following the wrong api), especially since the update to MCPE 0.15.x. If the issue persists with the latest version on Gitlab, I recommend to move your plugin folder and if that fixes the issue, then incrementally install them back a few at a time to narrow down the problem plugin.

I'll investigate further the best I can.

@PeratX if I am unable to find anything specific, could this be related to ab35ad31?

**Comment by ishitatsuyuki** [comment] 2016-07-20 08:08
Took a look, this is likely a plugin issue. Closing.

**Comment by FaanMaario** [comment] 2016-07-20 21:09
Thank you :)

**Comment by FaanMaario** [comment] 2016-07-21 01:44
@ZedCee Tested without plugins and updated to the latest version like you said but the message is again here. /

**Comment by ishitatsuyuki** [comment] 2016-07-21 01:46
I will reopen this so other people may take a look, however please ignore it for the meanwhile.

**Comment by FaanMaario** [comment] 2016-07-21 01:48
@ishitatsuyuki okay, sorry for the spam. ^^'

**Comment by ishitatsuyuki** [comment] 2016-07-22 05:29
Seems no one is reacting to this issue. I think it's not reproducible. Closing.

**Closed by ishitatsuyuki** 2016-07-22 05:29 UTC
