### ISSUE TITLE
Some chunks are saved empty

### ISSUE THREAD

**Issue by TheClimbing** [iTXTech/Genisys#2345] opened 2017-02-03 19:39 UTC
#### Issue description

Everywhere in the map including a Flat world there are holes which lead to the void.And I'm that's not from any of my plugins 
#### Steps to reproduce the issue

Just walk around and you will see a huge hole in the map leading to the void 
#### OS and versions

* Genisys:Genisys-1ed05b7
* PHP:7.0.14
* Server OS:Win7
* Game version: 1.0.0.16

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by JackNoordhuis** [comment] 2017-02-03 23:14
Get better internet and maybe your chunks will load. Without any proof of this happening or anyway to reproduce it we cannot confirm it or fix it.

**Comment by TheClimbing** [comment] 2017-02-04 00:06
@JackNoordhuis I can ensure you my internet is perfect. And this is a pic of a hole in Flat world. What steps I need to provide like:
1. Generate a FLAT world. 
2.Enter it. 
There isn't any Backtrace or anything there are just a holes in the map leading to the void. 
![screenshot_20170204-015948](https://cloud.githubusercontent.com/assets/13368636/22613134/83615b3c-ea7e-11e6-9205-c4ede2e75011.png)

3.Walk around

**Comment by yungtechboy1** [comment] 2017-02-04 00:38
@JackNoordhuis Might need to make Send Chunk Paccket Ack

**Comment by dktapps** [comment] 2017-02-04 09:54
Shut up with Nukkit blather. This is not a network issue.

As it happens, I've seen this issue on PigRaid servers; never did identify the cause though.

**Comment by JackNoordhuis** [comment] 2017-02-04 10:26
Seems more like a chunk sending issue rather than generation, probably caused by your server trying to keep too many chunks loaded so loading more causes problems.

**Comment by dktapps** [comment] 2017-02-04 10:39
@JackNoordhuis No, this is not a network issue. You wouldn't be able to see the sides of nearby chunks if that was the case. This is, I confirm, a generation issue. If you read the resulting generated chunks with an NBT editor, you will indeed see that they are completely empty.

**Comment by Qimie** [comment] 2017-02-05 00:01
Yeah,try to configure the settings.. Maybe you make ur server to force tick all chunks or you configure the max chunk to load too many until ur server cant even handle it.... This is my opinion bc I had this too.

**Comment by iTzAndrew33212** [comment] 2017-02-05 00:52
I have 4 worlds and that can confirm this dose not happening :) .. Must be due to your chucks not loading

**Comment by TheClimbing** [comment] 2017-02-05 09:24
And here @dktapps just  said twice thats its not a network issue and explained throughly why it's not. And again you are saying that chunks are not loading. Like do you want pictures of "Grand Canyon" in MinecraftPE

**Comment by Sandertv** [comment] 2017-02-05 09:37
I can confirm this is highly likely a generation issue. These holes don't appear at terrain that is already generated.

**Comment by dktapps** [comment] 2017-02-05 10:00
I believe this is due to a race-condition between the generator threads (asyncworkers) and level IO (main thread). I think what is happening is either:

a) some chunks are saved to disk before they are generated. This I think is the most likely scenario.
b) generator crashed when generating that chunk (unlikely for a flat world especially, since it essentially just generates a single chunk and copies it everywhere)

**Comment by TheClimbing** [comment] 2017-02-05 10:26
What I changed:
1.In chunk-sending:
     async-chunk-request from "true" to "false"
2.In chunk-generation:
      queue-size: from 4 to 2
      population-queue-size:  from 4 to 2
Now everything is fine

**Comment by TheClimbing** [comment] 2017-02-10 19:48
Still happens but rerely.Even after changing my settings which helped reducing the empty chunks number

**Comment by dktapps** [comment] 2017-02-17 11:47
Could somebody try https://github.com/pmmp/PocketMine-MP/pull/367 ?

**Comment by dktapps** [comment] 2017-03-07 10:37
Fixed as of 2c80000424fb2bf283374528708048e1ee9c70af.

**Closed by dktapps** 2017-03-07 10:37 UTC
Labels: bug, investigation needed
