### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by Andrew1481432** [iTXTech/Genisys#2281] opened 2016-12-19 12:45 UTC
* Genisys:
* PHP: 7.0.6
* Server OS: Debian

#### Crashdump, backtrace, memory dumps, plugins list or other files
Warning: assert(): Still 13 bytes unread in pocketmine\network\protocol\SpawnExperienceOrbPacket failed in phar:///home/genisys/PocketMine-MP.phar/src/pocketmine/network/Network.php on line 253

**Comment by dktapps** [comment] 2016-12-19 12:59
Duplicate of #2189 , please search the issue tracker before opening a new one.

**Closed by dktapps** 2016-12-19 12:59 UTC

**Comment by Andrew1481432** [comment] 2016-12-19 13:05
thank)
