### ISSUE TITLE
Network crash

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [iTXTech/Genisys#1489] opened 2016-07-19 21:26 UTC
Error: Uninitialized string offset: 0
File: /src/pocketmine/network/Network
Line: 227
Type: E_NOTICE

Code:
[218] 		$offset = 0;
[219] 		try {
[220] 			while ($offset < $len) {
[221] 				$pkLen = Binary::readInt(substr($str, $offset, 4));
[222] 				$offset += 4;
[223] 
[224] 				$buf = substr($str, $offset, $pkLen);
[225] 				$offset += $pkLen;
[226] 
[227] 				if (($pk = $this->getPacket(ord($buf{0}))) !== null) {
[228] 					if ($pk::NETWORK_ID === Info::BATCH_PACKET) {
[229] 						throw new \InvalidStateException("Invalid BatchPacket inside BatchPacket");
[230] 					}
[231] 
[232] 					$pk->setBuffer($buf, 1);
[233] 
[234] 					$pk->decode();
[235] 					$p->handleDataPacket($pk);
[236] 
[237] 					if ($pk->getOffset() <= 0) {

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

Genisys version: 1.2dev #620 [Protocol 81; API 2.0.0]
uname -a: Linux ast.localdomain 3.10.0-123.9.3.el7.x86_64 #1 SMP Thu Nov 6 15:06:03 UTC 2014 x86_64
PHP version: 7.0.2
Zend version: 3.0.0
OS : Linux, linux

Server uptime: 58 minutes 20 seconds
Number of loaded worlds: 8
Players online: 55/55

Is a old version but , i dont think you fixed it!!
And im back to genisys!! Cant find better fork :D

**Comment by matthew4444** [comment] 2016-07-19 21:31
use latest phar lol

**Comment by TDMidkwhatisxd** [comment] 2016-07-19 21:32
Is this fixed in latest version? I see network.php not updated for a month :0

**Comment by ZedCee** [comment] 2016-07-19 23:07
@TDMidkwhatisxd Glad to see the template was used.  It's important to help us repeat it on other platforms.  Thank you for doing so, it is appreciated. 

Were there any steps prior to this error occurring?  If so what was done.  This can further help us narrow down the issue.

As always I also recommend the latest phar, the issue may not actually be network.php, but something that utilizes its functions.

Very frequently there are issues caused by plugins(outdated or following the wrong api), especially since the update to MCPE 0.15.x.  If the issue persists with the latest version on Gitlab, I recommend to move your plugin folder and that fixes the issue, then incrementally install them back a few at a time to narrow down the problem plugin.

**Comment by TDMidkwhatisxd** [comment] 2016-07-20 03:20
I really dont know , it happens random!! :(  !

**Comment by TDMidkwhatisxd** [comment] 2016-07-20 03:26
buildmcpe.eu/plugins.zip   all plugins i use!!

**Comment by ZedCee** [comment] 2016-07-20 05:10
@TDMidkwhatisxd Could you provide that as a text based list.  Many of our devs use Windows and would be wary of downloading a zip file.
A cropped screen capture should be fine.  I apologize for any inconvenience.
This information will help our devs diagnose your issue.

**Comment by TDMidkwhatisxd** [comment] 2016-07-20 05:16
https://s32.postimg.org/6e8khupdh/Screenshot_2016_07_20_07_13_38.png

In zip file are all plugins that i use , some are custom or modded , if u use linux please check , or just scan it for viruses!!

**Comment by ZedCee** [comment] 2016-07-20 05:24
Are you presently running  Genisys-ab35ad3?
If not, please be sure to update from Gitlab and let us know if the issue persists.

I'll be sure this is seen as soon as it can be.  :arrow_down: 
@dktapps From the dump above, do you have an inkling to what may be going on?

**Comment by TDMidkwhatisxd** [comment] 2016-07-20 05:27
I was using start.sh from another fork + renamed as another fork , i dont wanna advertise!!
This is all that changed !! But i get this error , rarely , like someone trigger it (a modded client).

If it crash again , i will download genisys start.sh and update to latest!!

**Comment by ZedCee** [comment] 2016-07-20 05:49
@TDMidkwhatisxd Thanks, we appreciate anything you are able to do to help us expedite the process of finding the issue.  
I understand that the markdown language may be a bit confusing at first, but utilizing the template on a regular basis means your issue will be seen and looked into quicker. 
In keeping up to date be can be sure that any new errors are quickly discovered and squashed.

The devs for Genisys are quite busy, on top of that are living lives outside of Github.  This is the nature of open-source software and everyones contributions are what helps the software grow.

I highly recommend that you sign into gitter.im/iTXTech/genisys, as there you can communicate in a more realtime environment with the developers and myself.

**Comment by TDMidkwhatisxd** [comment] 2016-07-20 05:50
Ok , hope it helps :)

**Comment by ishitatsuyuki** [comment] 2016-07-20 08:02
I think you are running an outdated version. Also, this doesn't look like a crash. Closing.

**Closed by ishitatsuyuki** 2016-07-20 08:02 UTC

**Comment by TDMidkwhatisxd** [comment] 2016-07-20 10:16
I was sure !! You are a rude dev from here!! How this dont look like crash?
I have crash dump -_-

**Comment by ishitatsuyuki** [comment] 2016-07-20 10:32
I am sure that this is fixed in recent version already. Update before complaining.

**Comment by TDMidkwhatisxd** [comment] 2016-07-20 10:33
I understand , but u say is not a crash :0  :D!!
