### ISSUE TITLE
Lagg spikes 

### ISSUE THREAD

**Issue by Tolo0** [iTXTech/Genisys#1059] opened 2016-05-27 20:40 UTC
lately my servers been getting some serious lagg spikes. the servers fine one moment then suddenly lagg hits and all chat and commands freeze and players get like tped all over the place. iv  checked all plugins and they seem fine. is they any recommendations to reduce the lagg? 

Version: Genisys_1.1dev-416.phar

Running the server on Linux CentOS 6.

**Comment by Tolo0** [comment] 2016-05-27 20:45
Maybe this will help.  I don't fully understand it. 

http://timings.aikar.co/?url=16745651

**Comment by Tolo0** [comment] 2016-05-27 21:50
just noticed Genisys uses crazy amount of CPU.  is this normal?

![screenshot_20160527-224638](https://cloud.githubusercontent.com/assets/13458191/15622052/58e27b76-245d-11e6-81b9-2c5bc3d87ac3.png)

**Comment by FaanMaario** [comment] 2016-05-27 21:51
I have this me too

**Comment by Tolo0** [comment] 2016-05-27 22:19
my CPU just hit 135% isn't 100% ment to be max? why is genisys using so much 😕

**Comment by ishitatsuyuki** [comment] 2016-05-27 22:22
100 is one core. Can you take a 'perf top'?

**Comment by FaanMaario** [comment] 2016-05-27 22:22
For me, my PvP Faction server has enormous lags spikes and it's annoying for players; And the saddest is that I can't do anything to fix that :/

**Comment by Tolo0** [comment] 2016-05-27 22:33
how I do I perfect top?

**Comment by Tolo0** [comment] 2016-05-27 22:33
perf top*

**Comment by Aericio** [comment] 2016-05-27 22:35
He said in pocketmine.yml he set it to 4 cores, so probably that means 100% on one core, and 35% on another core maybe? But if it's set to 4 cores, it's supposed to equally make all the cores around the same usage so... idk

**Comment by PeratX** [comment] 2016-05-27 22:58
CommandReader's issue? @ishitatsuyuki

**Comment by ishitatsuyuki** [comment] 2016-05-28 03:14
@Tolo0 install and run 'perf top'. Should I explain more?
@PeratX definitely no.

**Comment by Tolo0** [comment] 2016-05-28 08:32
![screenshot_20160528-093202](https://cloud.githubusercontent.com/assets/13458191/15626219/205dab5e-24b7-11e6-8dd3-89e7bab4e20a.png)

**Comment by Tolo0** [comment] 2016-05-30 21:11
iv whitelisted my server and even with only 2 ppl on the lag spikes come. this is a genisys problem. fixing like should be 1st priority. no one likes a laggy server.

**Comment by Tolo0** [comment] 2016-05-30 21:12
using latest build also. still no beter Genisys_1.1dev-418.phar

**Comment by Aericio** [comment] 2016-05-31 01:32
10/10 support right here

**Comment by legoboy0215** [comment] 2016-06-05 23:33
Agreed. Genisys is using abnormal amount of CPU. Seriously, every server experiences it.

**Comment by Aericio** [comment] 2016-06-06 00:07
@legoboy0215 That's why we use ClearSky :)

**Comment by Muqsit** [comment] 2016-06-06 01:03
We are fixing it and before you start mentioning more forks, Genisys is the best among all. It has nearly every feature!

**Comment by legoboy0215** [comment] 2016-06-06 01:21
@Muqsit No offense, but how are you guys fixing it O_o

**Comment by Muqsit** [comment] 2016-06-06 01:25
@legoboy0215 Reducing code and using better functions? I'm not that sure, please don't judge me :3

**Comment by Muqsit** [comment] 2016-06-06 03:16
![x](https://cloud.githubusercontent.com/assets/15074389/15811145/3a1e5b76-2bae-11e6-9ac0-87cd4a9f1afa.PNG)
Am I the only one having balanced performance ;-;

**Comment by legoboy0215** [comment] 2016-06-06 03:21
Well, that is a expensive dedi there.
![2016-06-06_112047](https://cloud.githubusercontent.com/assets/12031248/15811206/bc5ed668-2bd8-11e6-907b-e723ba55fd81.png)
16 players. No, but the server runs quite smoothly. The CPU spike hits suddenly.

**Comment by Muqsit** [comment] 2016-06-06 03:25
True, happens to me when the uptime goes above 1.5 hours. Can you check your timings? If you're suffering from World Save event then that might be the problem, because that has the most delay as per my timings report.

**Comment by legoboy0215** [comment] 2016-06-06 04:19
Read PM forums message.

**Comment by Aericio** [comment] 2016-06-06 07:37
@Muqsit I do have to agree Genisys is "good", but it has too much built-in features lol. Synapse might even make it laggier though since its adding another built-in feature. Sorry for offtopic kinda

**Comment by Muqsit** [comment] 2016-06-06 08:06
True, true!

**Comment by PeratX** [comment] 2016-06-06 14:00
I will locate this issue. Please be patient :)

**Comment by legoboy0215** [comment] 2016-06-07 00:16
@PeratX Yes :)

**Comment by legoboy0215** [comment] 2016-06-10 12:06
Eh... What plugins are you running OP?

**Comment by Aericio** [comment] 2016-06-11 05:35
OP?

**Comment by legoboy0215** [comment] 2016-06-11 10:12
Original Poster

**Comment by Tolo0** [comment] 2016-06-14 07:08
iv recently switched to a dedicated server and haven't noticed much lagg. not sure if you fixed it or if it's just the beter performance machine in using.  my plugins are 

Plugins (36): PlanB v1.3.0, BuyCraft v1.2.2, TimeCommander v2, EconomyAPI v2.0.9, WorldProtect v2.2.0dev1, iProtector v3.1a, IP-Protect v1.1, CombatLogger v1.2.0, 1vs1 v0.0.5, ItemCloud v1.3, PerWorldChat v1.3, RestartMe v1.2.0, PurePerms v1.2.2, FactionsPro v1.4.1, ChatDefender v1.1.1, LimitedCreative v1.0.0, ItemCasePE v1.0.8, CustomAlerts v1.6, EconomyShop v2.0.7, SimpleAuth v1.8.1, MagicWE v0.0.5, HelpModifier v1.0.0, VoteReward v2.1, EconomySell v2.0.7, TapToDo v2.2.1, EssentialsPE v1.1.3, ClearLagg v1.1.0, OnlyMyWay v1.0-release, InstantRespawn v0.5.3, ChatCensor v1.4, BasicHUD v1.0.6, ItemEffects v2.5.0, EconomyLand v2.0.9, SimpleAuthHelper v2.0.1, MyPlot v1, PureChat v1.4.0

**Comment by legoboy0215** [comment] 2016-06-14 09:11
I'm sad. I can't afford a dedi lol.

**Comment by legoboy0215** [comment] 2016-06-16 08:29
@Muqsit Can you show me your pocketmine.yml?

**Comment by Muqsit** [comment] 2016-06-16 08:48
# Main configuration file for PocketMine-MP
# These settings are the ones that cannot be included in server.properties
# Some of these settings are safe, others can break your server if modified incorrectly
# New settings/defaults won't appear automatically on this file when upgrading.

settings:
 #Three-letter language code for server-side localization
 #Check your language code on https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes
 language: "eng"
 #Whether to send all strings translated to server locale or let the device handle them
 force-language: false
 #When server shut down, the players will get kicked and this is what will show on there screen.
 shutdown-message: "Â§bRumBenCraft FACTIONS is now restarting. Â§aClick the button below and join the server back. Â§eAlso, you've wasted 15+ seconds reading this message!"
 #Allow listing plugins via Query
 query-plugins: true
 #Show a console message when a plugin uses deprecated API methods
 deprecated-verbose: true
 #Enable plugin and core profiling by default
 enable-profiling: false
 #Will only add results when tick measurement is below or equal to given value (default 20)
 profile-report-trigger: 20
 #Number of AsyncTask workers.
 #Used for plugin asynchronous tasks, world generation, compression and web communication.
 #Set this approximately to your number of cores.
 #If set to auto, it'll try to detect the number of cores (or use 2)
 async-workers: auto

memory:
 #Global soft memory limit in megabytes. Set to 0 to disable
 #This will trigger low-memory-triggers and fire an event to free memory when the usage goes over this
 global-limit: 32000

 #Main thread soft memory limit in megabytes. Set to 0 to disable
 #This will trigger low-memory-triggers and fire an event to free memory when the usage goes over this
 main-limit: 32000

 #Main thread hard memory limit in megabytes. Set to 0 to disable
 #This will stop the server when the limit is surpassed
 main-hard-limit: 32000

 #Period in ticks to check memory (default 1 second)
 check-rate: 20

 #Continue firing low-memory-triggers and event while on low memory
 continuous-trigger: true

 #Only if memory.continuous-trigger is enabled. Specifies the rate in memory.check-rate steps (default 30 seconds)
 continuous-trigger-rate: 30

 garbage-collection:
  #Period in ticks to fire the garbage collector manually (default 30 minutes), set to 0 to disable
  #This only affect the main thread. Other threads should fire their own collections
  period: 36000

  #Fire asynchronous tasks to collect garbage from workers
  collect-async-worker: true

  #Trigger on low memory
  low-memory-trigger: true

 max-chunks:
  #Limit of chunks to load per player, overrides chunk-sending.max-chunks
  trigger-limit: 16

  #Do chunk garbage collection on trigger
  trigger-chunk-collect: true

  #Trigger on low memory
  low-memory-trigger: true

 world-caches:
  disable-chunk-cache: false
  low-memory-trigger: true

network:
 #Threshold for batching packets, in bytes. Only these packets will be compressed
 #Set to 0 to compress everything, -1 to disable.
 batch-threshold: 128
 #Compression level used when sending batched packets. Higher = Uses More CPU, Less = More Bandwidth Usage
 compression-level: 6
 #Use AsyncTasks for compression. Adds half/one tick delay, less CPU load on main thread
 async-compression: true
 #Experimental, only for Windows. Tries to use UPnP to automatically port forward
 upnp-forwarding: false

debug:
 #If > 1, it will show debug messages in the console
 level: 1
 #Enables /status, /gc
 commands: true

level-settings:
 #The default format that levels will use when created
 default-format: mcregion
 #If true, converts from a format that is not the default to the default format on load
 #NOTE: This is currently not implemented
 convert-format: false
 #Automatically change levels tick rate to maintain 20 ticks per second
 auto-tick-rate: false
 auto-tick-rate-limit: 20
 #Sets the base tick rate (1 = 20 ticks per second, 2 = 10 ticks per second, etc.)
 base-tick-rate: 1
 #Tick all players each tick even when other settings disallow this.
 always-tick-players: true

chunk-sending:
 #Amount of chunks sent to players per tick
 per-tick: 4
 #Amount of chunks sent around each player
 max-chunks: 16
 #Amount of chunks that need to be sent before spawning the player
 spawn-threshold: 1
 #Save a serialized copy of the chunk in memory for faster sending
 #Useful in mostly-static worlds where lots of players join at the same time
 cache-chunks: true

chunk-ticking:
 #Max amount of chunks processed each tick
 per-tick: 12
 #Radius of chunks around a player to tick
 tick-radius: 3
 light-updates: true
 clear-tick-list: true

chunk-generation:
 #Max. amount of chunks in the waiting queue to be generated
 queue-size: 4
 #Max. amount of chunks in the waiting queue to be populated
 population-queue-size: 6

ticks-per:
 animal-spawns: 400
 monster-spawns: 1
 autosave: 6000
 cache-cleanup: 900
spawn-limits:
  monsters: 30
  animals: 30
  water-animals: 1
  ambient: 15

auto-report:
 #Send crash reports for processing
 enabled: false
 send-code: true
 send-settings: true
 send-phpinfo: false
 host: crash.pocketmine.net

anonymous-statistics:
 #Sends anonymous statistics for data aggregation, plugin usage tracking
 enabled: false
 host: stats.pocketmine.net

auto-updater:
 enabled: false
 on-update:
  warn-console: false
  warn-ops: false
 #Can be development, beta or stable.
 preferred-channel: beta
 #If using a development version, it will suggest changing the channel
 suggest-channels: false
 host: www.pocketmine.net

aliases:
 daily: [kit beginner]
 shop: [warp shop]
 wild: [warp wild]
 removefx: [fx set null]
 #Examples:
 #showtheversion: version
 #savestop: [save-all, stop]

worlds:
 spawn: []
 world: []
 nether: []
 #These settings will override the generator set in server.properties and allows loading multiple levels
 #Example:
 #world:
 # seed: 404
 # generator: FLAT:2;7,59x1,3x3,2;1;decoration(treecount=80 grasscount=45)

**Comment by legoboy0215** [comment] 2016-06-16 10:51
Ok I can't use that lel. Optimized for a huge dedi.

**Comment by Driesboy** [comment] 2016-06-23 17:09
same if i run it my server have load 100

**Comment by Aericio** [comment] 2016-06-23 20:57
oh deer... 32 gb?

**Comment by Muqsit** [comment] 2016-06-24 01:38
That's because I not only run a whole network, but also host files and have a forums. Pocketmine doesn't make use of 100% RAM

**Comment by legoboy0215** [comment] 2016-06-24 01:43
It uses 100% CPU lol

**Comment by Driesboy** [comment] 2016-06-24 04:43
Yes haha
Op 24-jun.-2016 03:43 schreef "legoboy0215" <notifications@github.com>:

**Comment by Muqsit** [comment] 2016-06-24 08:17
Before running a server, make sure your system has 6+ cores if you'd like it to not lag much.

**Comment by legoboy0215** [comment] 2016-06-24 08:29
I have 8 cores.

**Comment by Muqsit** [comment] 2016-06-24 09:40
![screenshot_2016-06-24-12-39-51](https://cloud.githubusercontent.com/assets/15074389/16334297/8ed98d0a-39ac-11e6-98ff-d91aa4fd36cb.png)

**Comment by legoboy0215** [comment] 2016-06-24 10:53
lol I think it is a plugin problem. That is why I did not comment on this issue any more. Bur IDK any way to identify the issue.

**Comment by Aericio** [comment] 2016-06-24 19:55
6+ cores? cri. 2 cores do fine for me... #clearsky ^.^

**Comment by dktapps** [comment] 2016-06-26 14:12
The fix for [THE INFAMOUS MEMORY LEAK](https://github.com/iTXTech/Genisys/commit/e98738ca2d104ecc9e38436949c6b0854db20474) may resolve this problem. When leaking heavily, the CPU usage will be through the roof. Now that the leak is fixed, this problem might be fixed.

**Comment by JUSTaMod** [comment] 2016-06-26 23:20
eh. you beat me to saying that by 9 hours dkt. darn.

**Comment by legoboy0215** [comment] 2016-06-27 06:39
@dktapps I am currently testing it.

**Comment by PeratX** [comment] 2016-06-29 00:48
Since memory leak has fixed, useless entities are closed and server don't need to tick them, so this issue should be fixed.

**Comment by legoboy0215** [comment] 2016-06-29 04:43
@PeratX Reopen this. It is still not fixed.

**Comment by dktapps** [comment] 2016-07-06 12:25
#1357

**Comment by dktapps** [comment] 2016-07-06 12:25
oops, meant to just reference that

**Comment by Muqsit** [comment] 2016-07-06 14:55
@dktapps @PeratX Can you reproduce this issue? I don't think I can...

**Comment by dktapps** [comment] 2016-07-06 17:09
@Muqsit I can't reproduce it, no. My problem is more damn mem leaks -_- #1357

**Comment by Muqsit** [comment] 2016-07-09 06:38
@dktapps SAME!

**Comment by dktapps** [comment] 2016-07-09 12:41
Can anybody else with this issue confirm that #1416 fixes this problem?

**Comment by FaanMaario** [comment] 2016-07-09 12:54
Yup me, it works !

**Comment by dktapps** [comment] 2016-07-09 13:51
Closing this by way of https://github.com/iTXTech/Genisys/commit/dc8c0322db6d9f3656166a08f906cef864c36a03

**Closed by dktapps** 2016-07-09 13:51 UTC

**Comment by legoboy0215** [comment] 2016-07-12 01:38
I'll try it and give results when I get back home.
