### ISSUE TITLE
Bug - Invisible or empy chest

### ISSUE THREAD

**Issue by laurobeleche** [iTXTech/Genisys#2125] opened 2016-10-25 17:18 UTC
Many chests have disappeared when the server is closed. And the chests and some cases simply return empty. The high index of tiles in a world can cause this?

* Genisys: bef53a6
* PHP: 7.01
* Server OS: Windows 10
* Game version:  15.10

**Comment by dktapps** [comment] 2016-10-25 17:29
Duplicate of #803

**Closed by dktapps** 2016-10-25 17:29 UTC
