### ISSUE TITLE
Custom kick reason sometimes doesn't display

### ISSUE THREAD

**Issue by Striker209** [iTXTech/Genisys#1598] opened 2016-08-03 20:01 UTC
#### Issue description

When you get kicked from a server, the reason why you have been kicked doesn't appear on your screen. There is just the basic "Disconnected from server" that is written in the middle.

#### Steps to reproduce the issue

1. Connect to a Genesys server (username: Striker209)
2. Kick yourself using console or your client if you are an operator using /kick Striker209 Flying
3. You'll be just disconnected for "Disconnected from server"

#### OS and versions

* Genisys: e28d63b
* PHP:7.0.3
* Server OS: Ubuntu 15.04 (Linux)
* Game version: 0.15.4

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by XFuryMCPE** [comment] 2016-08-03 21:23
Confirmed. It happens about 2/3 of the time. But sometimes it shows the right message

**Comment by Mattia990** [comment] 2016-08-04 09:02
![immagine1](https://cloud.githubusercontent.com/assets/17655102/17396272/eefd06c0-5a32-11e6-96ec-a9bb375fc03c.png)
![immagine](https://cloud.githubusercontent.com/assets/17655102/17396273/ef1ec454-5a32-11e6-901c-7a54bc4b3744.png)

In my server it works

**Comment by dktapps** [comment] 2016-08-04 10:07
Reproduced. For me it happens maybe 1 in 3 times. It may be a client bug.

**Comment by legoboy0215** [comment] 2016-08-04 10:31
2 out of 3. I tested 12 times (yes literally) and 8 times it failed

**Comment by TheDiamondYT1** [comment] 2016-08-04 13:30
You can change the kick message by editing the the kick function but it doesn't work in plugins for me.

I have a fork of Genisys where i added an option to change the kick message in the `genisys.yml`, but it didnt work unless it was the same as the fallback message (`$this->getAdvancedProperty("blah", "fallback")`).

**Comment by Striker209** [comment] 2016-08-04 16:30
@Mattia990 Which version do you use ? It can be usefull for @dktapps to detect from where the bug comes

**Comment by Striker209** [comment] 2016-08-05 12:58
It also works sometimes for me, but it's unstable

**Comment by PeratX** [comment] 2016-08-07 01:03
That's because server send a DisconnectPacket and close the connection, Sometimes the DisconnectPacket hasn't reach the client then the server has closed the connection. Then it happens

**Comment by Striker209** [comment] 2016-08-07 09:38
Would there be a way to delay the two events?

**Comment by Dog2puppy** [comment] 2016-08-07 21:33
Have the server wait until the packet has arrived at the client before closing the connection.

**Comment by Striker209** [comment] 2016-08-08 19:33
So maybe a schedule ?

**Comment by Mattia990** [comment] 2016-08-15 17:58
@Striker209 I have been used the last version in that day

**Closed** 2016-08-23 08:38 UTC
