### ISSUE TITLE
Inventory lost

### ISSUE THREAD

**Issue by XiangZhao969** [iTXTech/Genisys#592] opened 2016-03-12 16:35 UTC
This appeared at startup, i think this is the reason
Notice: Object of class pocketmine\item\IronIngot could not be converted to int in phar:///home/game/Genisys*.phar/src/pocketmine/item/Item.php on line 1224

Notice: Object of class pocketmine\item\Steak could not be converted to int in phar:///home/game/Genisys*.phar/src/pocketmine/item/Item.php on line 1224

Notice: Object of class pocketmine\item\Steak could not be converted to int in phar:///home/game/Genisys*.phar/src/pocketmine/item/Item.php on line 1224

**Comment by Tee7even** [comment] 2016-03-12 20:18
These errors are most likely caused by faulty plugin. Inventory loss is not related to them. If the main reason of creating this issue is inventory loss, then it's basically a duplicate of #371.

**Closed** 2016-03-13 01:46 UTC
