### ISSUE TITLE
Local Server

### ISSUE THREAD

**Issue by kaitododoyt** [iTXTech/Genisys#1215] opened 2016-06-19 07:58 UTC
#### Issue description

Problems with local server of Genisys, i cant connect, i tried on android and the game closed, but this appear on console, on windows 10 edition nothing

#### Steps to reproduce the issue

You need have the port 19132 closed

#### OS and versions

* Genisys: Build #479 and all with protocol 0.15
* PHP: 7
* OS: Windows 10

#### Crashdump, backtrace or other files

Nothing, only cant disconnection

**Comment by ishitatsuyuki** [comment] 2016-06-19 07:59
What appears on console? Log please?

**Comment by kaitododoyt** [comment] 2016-06-19 08:36
nothing in console, is very strange. On my tablet and android cellphone the server is working now, i think was a plugin, but on windows 10 i cant join the game.

**Comment by ishitatsuyuki** [comment] 2016-06-19 08:51
Paste your whole log, nothing is not a description.

**Comment by kaitododoyt** [comment] 2016-06-19 09:00
This is all when i try to connect, the log and console is normal, without register when i try to connect

2016-06-19 [03:54:28] [Server thread/INFO]: 

		   PocketMine-iTX Genisys is a fork of PocketMine-MP, made by iTX Technologies LLC.
		   Version: 1.2dev-479
		   Target client Version: v0.15.0.0 alpha
		   Latest source code is available at https://github.com/iTXTech/Genisys
		   Donate link: http://pl.zxda.net/plugins/203.html
		   如果你在免费使用本核心，希望你可以进入上面的链接捐赠给我们，这会成为我们前进的动力。
		

2016-06-19 [03:54:28] [Server thread/INFO]: Loading pocketmine.yml...
2016-06-19 [03:54:28] [Server thread/INFO]: Loading genisys.yml...
2016-06-19 [03:54:28] [Server thread/INFO]: Loading server properties...
2016-06-19 [03:54:28] [Server thread/INFO]: Selected English (spa) as the base language
2016-06-19 [03:54:28] [Server thread/INFO]: Starting Minecraft: PE server version v0.15.0.0 alpha
2016-06-19 [03:54:28] [Server thread/INFO]: Opening server on 0.0.0.0:19132
2016-06-19 [03:54:28] [Server thread/INFO]: This server is running Genisys version 1.2dev-479 "Ikaros" (API 2.0.0)
2016-06-19 [03:54:28] [Server thread/INFO]: Genisys is distributed under the GPL License version 3 and later
2016-06-19 [03:54:28] [Server thread/INFO]: Loading AntiCheat v2.3.1
2016-06-19 [03:54:29] [Server thread/INFO]: Loading BW v1.2
2016-06-19 [03:54:29] [Server thread/INFO]: Loading CTF_DODO v1.1.0
2016-06-19 [03:54:29] [Server thread/INFO]: Loading EconomyAPI v2.0.9
2016-06-19 [03:54:29] [Server thread/INFO]: Loading EconomyShop v2.0.7
2016-06-19 [03:54:29] [Server thread/INFO]: Loading EmptyWorld v1.1.0
2016-06-19 [03:54:29] [Server thread/INFO]: Loading EntityManager v2.7
2016-06-19 [03:54:29] [Server thread/INFO]: Loading HereAuth v1.0-Beta#174
2016-06-19 [03:54:29] [Server thread/INFO]: Loading HungerGamesFlo v3.0.0
2016-06-19 [03:54:29] [Server thread/INFO]: Loading KitsDoDo v2.0.0
2016-06-19 [03:54:29] [Server thread/INFO]: Loading ManyWorlds v2.0.3
2016-06-19 [03:54:29] [Server thread/INFO]: Loading PartDoDo v1 alpha
2016-06-19 [03:54:29] [Server thread/INFO]: Loading PureEntities v1.0
2016-06-19 [03:54:29] [Server thread/INFO]: [PureEntities]All entities were registered
2016-06-19 [03:54:29] [Server thread/INFO]: Loading PvPWorlds v1
2016-06-19 [03:54:29] [Server thread/INFO]: Loading Slapper v1.2.9.3
2016-06-19 [03:54:29] [Server thread/INFO]: Loading SmashDoDo v1.1.0
2016-06-19 [03:54:29] [Server thread/INFO]: Loading SpecDoDo v1.0
2016-06-19 [03:54:29] [Server thread/INFO]: Loading TapToDo v2.2.1
2016-06-19 [03:54:29] [Server thread/INFO]: Loading UHCDoDo v2.1.0
2016-06-19 [03:54:29] [Server thread/INFO]: Loading WorldEdit v0.5.2
2016-06-19 [03:54:29] [Server thread/INFO]: Loading xyz v1.0.1
2016-06-19 [03:54:29] [Server thread/INFO]: [xyz] /xyz loaded
2016-06-19 [03:54:29] [Server thread/INFO]: Enabling AntiCheat v2.3.1
2016-06-19 [03:54:29] [Server thread/INFO]: [AntiCheat] AntiCheat Activated
2016-06-19 [03:54:29] [Server thread/INFO]: [AntiCheat] Shield Activated
2016-06-19 [03:54:29] [Server thread/INFO]: [AntiCheat] AntiCheat v2.3.1 [Wolverine]
2016-06-19 [03:54:29] [Server thread/INFO]: Enabling EmptyWorld v1.1.0
2016-06-19 [03:54:29] [Server thread/INFO]: Enabling EntityManager v2.7
2016-06-19 [03:54:29] [Server thread/INFO]: [EntityManager]Plugin has been enabled
2016-06-19 [03:54:29] [Server thread/INFO]: Enabling PureEntities v1.0
2016-06-19 [03:54:29] [Server thread/INFO]: [PureEntities]Plugin has been enabled
2016-06-19 [03:54:29] [Server thread/INFO]: Preparing level "world"
2016-06-19 [03:54:29] [Server thread/INFO]: Preparing level "nether"
2016-06-19 [03:54:29] [Server thread/INFO]: Enabling BW v1.2
2016-06-19 [03:54:29] [Server thread/INFO]: [BW] [Bedwars] BedWars Habilitado!
2016-06-19 [03:54:29] [Server thread/INFO]: [BW] Arena bw Cargada correctamente!
2016-06-19 [03:54:29] [Server thread/INFO]: Preparing level "Oriental"
2016-06-19 [03:54:29] [Server thread/NOTICE]: Level "lob" not found
2016-06-19 [03:54:29] [Server thread/INFO]: [BW] Arena test Cargada correctamente!
2016-06-19 [03:54:29] [Server thread/INFO]: Preparing level "Tron"
2016-06-19 [03:54:29] [Server thread/NOTICE]: Level "lob" not found
2016-06-19 [03:54:29] [Server thread/INFO]: Enabling CTF_DODO v1.1.0
2016-06-19 [03:54:29] [Server thread/INFO]: [CTF_DODO] CTF by KaitoDoDo
2016-06-19 [03:54:29] [Server thread/NOTICE]: Level "uhc3" not found
2016-06-19 [03:54:29] [Server thread/INFO]: Enabling EconomyAPI v2.0.9
2016-06-19 [03:54:29] [Server thread/NOTICE]: [EconomyAPI] Provider was set to: Yaml
2016-06-19 [03:54:29] [Server thread/NOTICE]: [EconomyAPI] Auto save has been set to interval : 10 min(s)
2016-06-19 [03:54:29] [Server thread/INFO]: [EconomyAPI] Checking for updates... It may be take some while.
2016-06-19 [03:54:30] [Server thread/NOTICE]: [EconomyAPI] Globally 6000 servers use EconomyS.
2016-06-19 [03:54:30] [Server thread/INFO]: Enabling EconomyShop v2.0.7
2016-06-19 [03:54:30] [Server thread/INFO]: Enabling HereAuth v1.0-Beta#174
2016-06-19 [03:54:30] [Server thread/INFO]: Enabling HungerGamesFlo v3.0.0 ServerKAI
2016-06-19 [03:54:30] [Server thread/INFO]: [HungerGamesFlo] HungerGames by KaitoDoDo
2016-06-19 [03:54:30] [Server thread/NOTICE]: Level "flat" not found
2016-06-19 [03:54:30] [Server thread/INFO]: Enabling KitsDoDo v2.0.0 nether
2016-06-19 [03:54:30] [Server thread/INFO]: [KitsDoDo] KITS KaitoDoDo
2016-06-19 [03:54:30] [Server thread/INFO]: Enabling ManyWorlds v2.0.3
2016-06-19 [03:54:30] [Server thread/INFO]: Enabling PartDoDo v1 alpha
2016-06-19 [03:54:30] [Server thread/INFO]: [PartDoDo] Part by Kai
2016-06-19 [03:54:30] [Server thread/INFO]: Enabling PvPWorlds v1
2016-06-19 [03:54:30] [Server thread/INFO]: [PvPWorlds] PvPWorlds Loaded!
2016-06-19 [03:54:30] [Server thread/INFO]: [PvPWorlds] No-PvP Worlds: lobby, parkour, world
2016-06-19 [03:54:30] [Server thread/INFO]: Enabling Slapper v1.2.9.3
2016-06-19 [03:54:30] [Server thread/INFO]: Enabling SmashDoDo v1.1.0
2016-06-19 [03:54:30] [Server thread/INFO]: [SmashDoDo] SmashDoDo by KaitoDoDo
2016-06-19 [03:54:30] [Server thread/NOTICE]: Level "Smash" not found
2016-06-19 [03:54:30] [Server thread/INFO]: Enabling SpecDoDo v1.0
2016-06-19 [03:54:30] [Server thread/INFO]: [SpecDoDo] SPECTERDoDo Habilitadisimo
2016-06-19 [03:54:30] [Server thread/INFO]: Enabling SwaggyMOTD v1.0.0
2016-06-19 [03:54:30] [Server thread/INFO]: [SwaggyMOTD] Enabled!
2016-06-19 [03:54:30] [Server thread/INFO]: Enabling TapToDo v2.2.1
2016-06-19 [03:54:30] [Server thread/INFO]: Enabling UHCDoDo v2.1.0
2016-06-19 [03:54:30] [Server thread/INFO]: [UHCDoDo] UHC by KaitoDoDo
2016-06-19 [03:54:30] [Server thread/NOTICE]: Level "UHC" not found
2016-06-19 [03:54:30] [Server thread/INFO]: Enabling WorldEdit v0.5.2
2016-06-19 [03:54:30] [Server thread/INFO]: [WorldEdit] -MCG76 WorldEdit Enabled
2016-06-19 [03:54:30] [Server thread/INFO]: Enabling xyz v1.0.1
2016-06-19 [03:54:30] [Server thread/INFO]: [xyz] /xyz enabled.
2016-06-19 [03:54:30] [Server thread/INFO]: Starting GS4 status listener
2016-06-19 [03:54:30] [Server thread/INFO]: Setting query port to 19132
2016-06-19 [03:54:30] [Server thread/INFO]: Query running on 0.0.0.0:19132
2016-06-19 [03:54:30] [Server thread/INFO]: Default game type: Survival Mode
2016-06-19 [03:54:30] [Server thread/INFO]: Done (2.405s)! For help, type "help" or "?"

**Comment by ishitatsuyuki** [comment] 2016-06-19 09:01
And you have mentioned that 19132 is closed. Isn't it the problem?

**Comment by kaitododoyt** [comment] 2016-06-19 09:05
i was thinking this, but now i open the port and still nothing

**Comment by ishitatsuyuki** [comment] 2016-06-19 09:08
You are probably connecting to a wrong host. Closing for insufficient details.

If the game crash, check the open issues.

**Closed by ishitatsuyuki** 2016-06-19 09:08 UTC

**Comment by dktapps** [comment] 2016-06-19 09:15
Windows 10 edition cannot connect to servers hosted on the same machine any more. This is most likely a client problem. Also if you are still having crashes refer to #1206 ; the comments may help you resolve your crashes.

**Comment by kaitododoyt** [comment] 2016-06-19 09:19
thanks, but now i can connect adding the server with external IP

**Comment by eDroidPlayzYT** [comment] 2016-06-26 18:06
i have the same issue. even if i connect with external ip.

**Comment by timm1292** [comment] 2016-06-27 17:14
this is annoying i got the same problem nothing appearing in the console i checked everything but it didnt work on the same machine it works on android but yeah pc is more easy

**Comment by dktapps** [comment] 2016-07-12 10:26
Thank @robske110 for this fix.
- Make sure the game is closed
- Open PowerShell as administrator
- Run this command: `CheckNetIsolation LoopbackExempt -a -n="Microsoft.MinecraftUWP_8wekyb3d8bbwe"`
- Try and connect to your server on the same computer
- Bingo :P

**Comment by timm1292** [comment] 2016-07-14 16:38
@dktapps Its not working for me. tried it 3 times still shows nothing the console triple checked everything but nothing.  :(

**Comment by dktapps** [comment] 2016-07-14 16:44
@timm1292 then you have some other issue that is not the fault of Win10 or Genisys, because it works for me.

**Comment by timm1292** [comment] 2016-07-14 16:46
Ah shiit thnx anyway

**Comment by timm1292** [comment] 2016-07-23 13:45
I got it working after changing something in the options.txt file from minecraft
1. goto %localappdata%\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\minecraftpe
2. open options.txt 
3.find dev_uselocalserver:0 and put it to 1 (dev_uselocalserver:1) save it and poof

**Comment by dktapps** [comment] 2016-07-23 15:40
@timm1292 I'll add that to the wiki, thanks for sharing the information. :)

**Comment by timm1292** [comment] 2016-07-23 16:13
No problem : )

**Comment by GlitchPlayer** [comment] 2016-07-31 06:24
Worked at 0.15.3. but in 0.15.4, not anymore. I'm trying now in uninstalling.

**Comment by timm1292** [comment] 2016-07-31 06:51
Did you try both of these @GlitchPlayer

**Comment by GlitchPlayer** [comment] 2016-07-31 06:53
Yes. I can see me server online but I can't connect

**Comment by timm1292** [comment] 2016-07-31 06:58
Later*

**Comment by GlitchPlayer** [comment] 2016-07-31 08:20
I reproduced the problem!
Upon opening mcwe. Any LAN games will be not available to join (Tested with playing with my brother)
When I opened a world and came back to main menu, Every LAN can be now connected.

Idk why is this happening but I fixed it :3

**Comment by thebigsmileXD** [comment] 2017-01-10 11:28
@timm1292 your fix worked for me, and i did reset the option and tried @GlitchPlayer's fix, both worked. Thx! (Add this stuff to installer or the PocketMine.php startup?)

**Comment by GlitchPlayer** [comment] 2017-01-11 03:50
@thebigsmileXD I haven't tested this on new versions

**Comment by techboy04** [comment] 2017-04-09 03:34
I am having trouble as well

**Comment by techboy04** [comment] 2017-04-09 03:37
I am having trouble as well
