### ISSUE TITLE
0.15.0 Client Crash-due to PE-unknown blocks

### ISSUE THREAD

**Issue by biswarm22** [iTXTech/Genisys#1206] opened 2016-06-18 14:36 UTC
#### Issue description

When a player joins, after the chunks load the client crashes. I tried to remove all plugins, but it had the same result so it is not a plugin issue. I also tried deleting all player data and triing it on other deivces. 
#### Steps to reproduce the issue

put unsupported blocks from pc into a world and the client crashes right away
#### OS and versions

* Genisys: c037d17d3d0aa9f2347e28a5cefa2ff34f3e0869
* PHP: 7
* OS: Windows 10

#### UPDATE:  TEMP FIX
BEFORE: Backup your world before doing this in case anything happens 
1. Download latest satble build of MCedit here: http://www.mcedit.net/downloads.html
2. Install MCEDIT
3. Open Mcedit and import your world in
4. Copy your world and paste it into a blank MCPE world
5. Copy and paste from the MCPE world to Anvil world.
6. Save the anvil world
NOTE: This may make your signs disappear and will replace non MCPE blocks with another block such as white wool

**Comment by dktapps** [comment] 2016-06-18 14:38
Please try and remove all mobs using a plugin such as ClearLagg or GrabBag.

**Comment by FaanMaario** [comment] 2016-06-18 14:47
I have the same problem I guess; 
Players can't join my servers ("locating server" and instantly "disconnected from server") I tried removing all plugins but nothing :/

**Comment by dktapps** [comment] 2016-06-18 15:04
@FaanMaario I think he's referring to an actual crash. What you're referring to is a connection problem, not a crash.

**Comment by FaanMaario** [comment] 2016-06-18 15:09
@dktapps Oh okay, sorry for this misunderstanding ^^'
But, do you know how to fix this connection problem?

**Comment by dktapps** [comment] 2016-06-18 15:11
@FaanMaario It's most likely a network issue. Make sure your internet connection is working properly. You could also try opening the server on a different port. This is not a Genisys issue.

**Comment by FaanMaario** [comment] 2016-06-18 15:12
@dktapps Thank you, I'll try to change server port!

**Comment by CLiu13** [comment] 2016-06-18 15:50
I am having the very same issue, using a PC imported map in Anvil format. Previously worked before 0.15.0 came out. Tried on different ports and different machines as well.

**Comment by dktapps** [comment] 2016-06-18 16:02
Strange. This seems to be related directly to mcanvil.

**Comment by Driesboy** [comment] 2016-06-18 16:02
ITS NOT ONLY FOR ANVIL WORLD 
my anvil world load without crash!

**Comment by Muqsit** [comment] 2016-06-18 16:52
Happens to my mcregion world but I think I know of a fix for this!

**Comment by dktapps** [comment] 2016-06-18 16:55
@Muqsit By all means, if you can fix it go ahead. I can't reproduce it so I can't diagnose it.

**Comment by biswarm22** [comment] 2016-06-18 17:01
@FaanMaario Your Proberaum is likely a network problem. For me it connects to the server then it crashes after the world loads on the client

**Comment by MichaelM04** [comment] 2016-06-18 17:10
I also have a Anvil PC Map which crashes upon join of world (no mobs) but after experimentation its only in a 50x50 radius of the original set spawn, if you force spawn yourself elsewhere in the world it works fine. Only when you come to spawn area it crashes

**Comment by biswarm22** [comment] 2016-06-18 17:14
@dktapps I can give you the download for he world if you want just email me at BluiCraftteam@gmail.com

**Comment by MichaelM04** [comment] 2016-06-18 17:15
Non related to Anvil worlds crash issue, many people are confusing this issue with the mob issue, do what @dktapps said and use a entities remover and you'll be fine, test these methods before assuming one of them is the issue

**Comment by Driesboy** [comment] 2016-06-18 17:16
Wrong i use it on my mcregion world and it crash!
Op 18-jun.-2016 19:15 schreef "Michael" <notifications@github.com>:

**Comment by biswarm22** [comment] 2016-06-18 17:16
@MichaelM04 I don't have any mobs in my world I have TimeCommandet set to /lag clearall every min

**Comment by MichaelM04** [comment] 2016-06-18 17:18
Have you tryed going to a different area in the world? A couple hundred blocks should do

**Comment by biswarm22** [comment] 2016-06-18 17:18
@Driesboy Is your server hub .mca or .mcr

**Comment by biswarm22** [comment] 2016-06-18 17:19
@MichealM04 I can't go to a different area because it crashes once the world loads

**Comment by MichaelM04** [comment] 2016-06-18 17:20
@biswarm22 You have to teleport the player to a different area before the client disconnects, took me a while but it worked

**Comment by Driesboy** [comment] 2016-06-18 17:22
Mca
Op 18-jun.-2016 19:18 schreef "BluiCraft" <notifications@github.com>:

**Comment by dktapps** [comment] 2016-06-18 17:23
@biswarm22 yes please.

**Comment by CLiu13** [comment] 2016-06-18 17:24
I believe this has something to do with PC blocks that are not supported in PE?

**Comment by MichaelM04** [comment] 2016-06-18 17:25
@CLiu13 The world works if you downgrade back to 0.14.3

**Comment by Driesboy** [comment] 2016-06-18 17:28
@CLiu13 yes that could be 
my crashed map is builded on pc and have pc blocks that are not supported in PE!

**Comment by biswarm22** [comment] 2016-06-18 17:28
@MichaelM04 @CLiu13  @Driesboy  yes, but in minecraft 0.14.3 it works

**Comment by Driesboy** [comment] 2016-06-18 17:29
@biswarm22 but 0.15.0 is not 0.14.3!

**Comment by dktapps** [comment] 2016-06-18 17:29
I can confirm this is to do with unsupported blocks.
I used a world editor to set a block ID not supported in PE and the game crashed straight away.

**Comment by biswarm22** [comment] 2016-06-18 17:29
it might be that in 0.14.3, unsupported blocks were turned into a strange brown block with green stuff but in 0.15.0 that might be broken

**Comment by linuzo** [comment] 2016-06-18 17:29
Yes, some of my PC made worlds in Anvil work and some don't so it's not fair to say it's related to that directly. Perhaps there is an unsupported block so currently we rebuilt maps to make it work.  I'm going to see about enabling developer mode to see if I can get some errors..

**Comment by MichaelM04** [comment] 2016-06-18 17:29
@Driesboy If the maps blocks were never converted this likely is the issue

**Comment by biswarm22** [comment] 2016-06-18 17:30
@MichaelM04 thats what i thought at first

**Comment by Driesboy** [comment] 2016-06-18 17:32
@MichaelM04 the world is always online since 1 juni they always converted

**Comment by biswarm22** [comment] 2016-06-18 17:33
so how can we fix

**Comment by CLiu13** [comment] 2016-06-18 17:33
Well, looks like by popular consensus my guess was right. :P

On a side note, I believe a solution might be to load the map in MCEdit and remove any non-PE blocks.

**Comment by Driesboy** [comment] 2016-06-18 17:34
a system that scan all blocks and if the block id not is imported in minecraft
it will be a update block

**Comment by CLiu13** [comment] 2016-06-18 17:35
Is there a tool available that simply scans the whole world for non-PE blocks and replaces them?

**Comment by biswarm22** [comment] 2016-06-18 17:35
@CLiu13 is there a way to make it into another block like in 0.14.3

**Comment by MichaelM04** [comment] 2016-06-18 17:35
PM Importer does that

**Comment by Driesboy** [comment] 2016-06-18 17:36
yes but i cannot in that world anymore!

**Comment by CLiu13** [comment] 2016-06-18 17:36
https://github.com/Muirfield/pmimporter Seems outdated...

**Comment by biswarm22** [comment] 2016-06-18 17:37
@CLiu13 i used to have that plugin, it no longer works

**Comment by biswarm22** [comment] 2016-06-18 17:38
@Muqsit do you know the fix for this

**Comment by CLiu13** [comment] 2016-06-18 17:39
@Driesboy If PMImporter still works, you don't need to join the world anymore - just run the commands via console.

I can try updating this to PHP7, and I will post a version here later.

**Comment by biswarm22** [comment] 2016-06-18 17:39
@CLiu13 ok thanks

**Comment by MichaelM04** [comment] 2016-06-18 17:40
I converted it to php7 its never worked for me correctly. Someone told me it works from the command line, I never tryed

**Comment by biswarm22** [comment] 2016-06-18 17:41
ya i tried it and it said a error message cannot convert and showed error message

**Comment by Muqsit** [comment] 2016-06-18 17:41
Were there any inventories or blocks secretly removed in 15?

**Comment by CLiu13** [comment] 2016-06-18 17:42
@MichaelM04 Can you send me your converted-to-PHP7 version?

**Comment by biswarm22** [comment] 2016-06-18 17:42
https://github.com/Muirfield/pmimporter/issues/2

**Comment by biswarm22** [comment] 2016-06-18 17:44
@Muqsit maybe it is the block that replaced unknown blocks

**Comment by CLiu13** [comment] 2016-06-18 17:46
Can someone test this out? Item IDs for the UPDATE! Blocks are 248 and 249.

**Comment by biswarm22** [comment] 2016-06-18 17:51
@Clui13 what?

**Comment by dktapps** [comment] 2016-06-18 18:01
UPDATE! blocks don't crash the game. It's unrecognized IDs which cause crashes. For example Beacons (ID 138) will cause a crash.

**Comment by dktapps** [comment] 2016-06-18 18:01
So any block that would ordinarily be an update! block causes crashes, _except_ actual update! blocks. This makes lots of sense.

**Comment by Muqsit** [comment] 2016-06-18 18:03
@dktapps Can you share your pocketmine.yml file with us?

**Comment by dktapps** [comment] 2016-06-18 18:04
http://pastebin.com/44Nzxhei

**Comment by biswarm22** [comment] 2016-06-18 18:19
@dktapps so all we need to do is to replace the unknown block ids with others?

**Comment by dktapps** [comment] 2016-06-18 18:20
@biswarm22 I think so, if you can find a way to replace the unknown blocks without crashing

**Comment by MichaelM04** [comment] 2016-06-18 19:21
I'll try to do a plugin for this

**Comment by CLiu13** [comment] 2016-06-18 19:40
Issue resolved for me. PMImporter works (use the dev branch).

**Comment by MichaelM04** [comment] 2016-06-18 20:53
![screenshot_2016-06-18-15-51-41](https://cloud.githubusercontent.com/assets/16037546/16173612/cac7819e-356c-11e6-97ec-58edc470410f.png)

So far this is what I've got xD

**Comment by Skull3x** [comment] 2016-06-18 22:35
Lol

**Comment by biswarm22** [comment] 2016-06-19 00:19
lol

**Comment by biswarm22** [comment] 2016-06-19 00:20
@CLiu13 this branch? https://github.com/Muirfield/pmimporter/tree/dev

**Comment by biswarm22** [comment] 2016-06-19 00:25
@CLiu13 how do you use it

**Comment by biswarm22** [comment] 2016-06-19 00:27
@CLiu13 can you get a phar download link i cant convert it into phar

**Comment by CLiu13** [comment] 2016-06-19 00:27
Yes, use https://github.com/Muirfield/pmimporter/tree/dev and carefully read the documentation at the bottom.

**Comment by biswarm22** [comment] 2016-06-19 00:41
@CLiu13 i tried putting the commands into the console and they did not work

**Comment by ishitatsuyuki** [comment] 2016-06-19 00:42
Please bring the discussion to a chat

**Comment by biswarm22** [comment] 2016-06-19 00:44
@ishitatsuyuki ok

**Comment by biswarm22** [comment] 2016-06-19 00:45
@CLiu13 only works in linux

**Comment by CLiu13** [comment] 2016-06-19 00:48
As ishitatsuyuki said, we are not supposed to discuss this here anymore, and I agree. If you do not have a Linux machine, then you are out of luck.

**Comment by Adam1609** [comment] 2016-06-19 03:46
I bring my survival world from 1.9 PC and it's completely normal, why do you have an error for this?

**Comment by biswarm22** [comment] 2016-06-19 10:09
@Adam1609 it is because if you use blocks that are in pc, but not in pe in your 1.9 PC world then you transfer the Pc world to the server, it crashes

**Comment by biswarm22** [comment] 2016-06-19 12:37
#### UPDATE:  FIX
BEFORE: Backup your world before doing this in case anything happens 
1. Download latest satble build of MCedit here: http://www.mcedit.net/downloads.html
2. Install MCEDIT
3. Open Mcedit and import your world in
4. Copy your world and paste it into a blank MCPE world
5. Copy and paste from the MCPE world to Anvil world.
6. Save the anvil world
NOTE: This may make your signs disappear and will replace non MCPE blocks with another block suck as white wool

**Comment by biswarm22** [comment] 2016-06-19 12:42
@Driesboy send me the world and i can convert it for you. email: bluicraftteam@gmai.com

**Comment by ishitatsuyuki** [comment] 2016-06-19 12:46
What are you doing? Do you want a hard close?

**Comment by Driesboy** [comment] 2016-06-19 12:47
Yes but i have npcs in my world
Op 19-jun.-2016 14:42 schreef "BluiCraft" <notifications@github.com>:

**Closed by ishitatsuyuki** 2016-06-19 12:46 UTC

**Comment by biswarm22** [comment] 2016-06-19 12:48
@Driesboy when i convert it you will have to remake the npcs

**Comment by Driesboy** [comment] 2016-06-19 12:52
And my signs?
Op 19-jun.-2016 14:48 schreef "BluiCraft" <notifications@github.com>:

**Comment by biswarm22** [comment] 2016-06-19 12:55
@Driesboy yes

**Comment by biswarm22** [comment] 2016-06-19 12:56
@Driesboy In my world, all my NPC's disappeared and i had to replace all signs

**Comment by Driesboy** [comment] 2016-06-19 12:56
but i think we can fix this

**Comment by biswarm22** [comment] 2016-06-19 12:59
@Driesboy the signs are just messed up. they show up as this (text$) hhhff, or something like that

**Comment by Driesboy** [comment] 2016-06-19 13:02
ok give me your mail i will send

**Comment by biswarm22** [comment] 2016-06-19 13:07
@Driesboy bluicraftteam@gmail.com

**Comment by Driesboy** [comment] 2016-06-19 13:35
ok i will do that tomorrow

**Comment by dktapps** [comment] 2016-06-19 15:35
I have confirmed that this is an MCPE client bug, and nothing to do with Genisys. Hopefully future MCPE updates will resolve this problem.

**Comment by Heroata** [comment] 2016-06-23 05:15
![image](https://cloud.githubusercontent.com/assets/10375421/16292470/6a815628-391a-11e6-980a-9d058adf9d5d.png)
This red entities crashing the client. When you see it, client crashing. But its hard to select all of them. @biswarm22 can you more explain the solution? I'm working on a big server project but this is a big wall on our way.

**Comment by remotevase** [comment] 2016-06-24 13:30
So, really, the simple fix is to find some way or another to change the world to anvil format, right? I'm sorry if I got it wrong, kinda confused, but I think that's what you need to do

**Comment by Heroata** [comment] 2016-06-24 14:45
OMG I was trying convert map to leveldb oh god >.<

**Comment by remotevase** [comment] 2016-06-24 15:46
@heroata oh god

**Comment by Driesboy** [comment] 2016-06-27 17:45
@biswarm22 when my worlds are ready?

**Comment by RocoWayne** [comment] 2016-07-11 14:35
Can somebody list wich PC blocks are the cause of the crash in 0.15 servers? So maybe i can code a plugin that select an replace this blocks

**Comment by ZedCee** [comment] 2016-07-12 15:37
_@RocoWayne and to whomever may be interested,_
Next to erroneous entities, which by this point is mostly fixed, there seems to be client crash related issues with villages, mountainous regions, and certain types of NBT data with entities or tile entities.

Converted blocks discovered to definitely be a culprit of crashes in imported PC Anvil maps:
_Grass Path 
Beetroots_ 

Blocks breaking when trying to switch back to Anvil from a converted region
_SkyBlocks (<- MCEdit can't handle the McRegion format because of these)_

Using **PMImporter** works fine for converting them, mind you the default rules are zealous and most can be changed to their respective blocks.  Whatever can't be converted to the respective replacement gets an update! block; also breaks using MCEdit because of SkyBlocks and related barrier blocks.  After converting, the only way to see what lacked PE IDs and was switched to "update!" is via client.  
 _(https://github.com/Muirfield/pmimporter/tree/dev)_
 _(https://github.com/Khroki/MCEdit-Unified)_

Regardless, **this is not a Genysis error**; the server sends the chunks and runs normally.  However if you insist exploring in a given area, Genysis will start spitting out NBT errors about line 486, if I remember correctly, then start rampantly deleting chunks to correct incorrect NBT string lengths (Again going from memory; the string length was too long I think).  In my map, I was able to explore after restarting every time a chunk was offed for mere seconds until it deleted most of the local town and some random area in the middle of some mountains (likely point x=0 z=0); With some intervention and 30 or more chunks deleted, removing the GrassBlocks and Beetroots finished the correction; I do not know what the other mystery block was that caused the crash in the mountains, I suspected monster eggs, but theyre all over the map, so scratch those off the list.

Anyway I'm off to push some changes somewhere, but I would like to see if a temporary fix for my broken maps could be found before we wait for a Mojang update to fix this.  Not fond of having to teleport everyone around to my different islands, I want them all in a master map.

**Comment by robske110** [comment] 2016-07-12 17:14
why closed

**Comment by barnseyminesuk** [comment] 2016-08-07 09:55
Anyone do this for me?

**Comment by ishitatsuyuki** [comment] 2016-08-07 12:43
@barnseyminesuk This is not a chat, and do not spam here. Use chat service written in README or else you will get banned for spamming.

**Comment by TheDiamondYT1** [comment] 2016-08-16 07:34
@dktapps Try and install a map from 1.9

**Comment by Heroata** [comment] 2016-08-16 20:04
@TheDiamondYT1 For example a map that built on Minecraft CE 1.4, if I open dat world on 1.9, will it work on Minecraft PE 0.15.x Pocketmine?

**Comment by mote166** [comment] 2016-08-17 12:53
u can remove the blocks manually using block launcher cuz block launcher actually replaces unsupported blocks to an update! block

**Comment by Heroata** [comment] 2016-08-17 22:55
YOU ARE KIDDING ME! I'm trying!

**Comment by RocoWayne** [comment] 2016-09-23 17:09
how can i do that @mote166 ?
