### ISSUE TITLE
Effect Particles

### ISSUE THREAD

**Issue by GenisysFTW** [iTXTech/Genisys#1577] opened 2016-08-01 15:38 UTC
This has been an issue since 0.15 release.
$effect->setVisible(false);
DOES WORK but it will replace the effect's particle with a black particle.

* Genisys: 1.8.0 | #3832426
* PHP: 7.0.8
* Server OS: Ubuntu 14.04 LTS
* Game version: 0.15.1, 0.15.2, 0.15.3, 0.15.4

**Comment by Muqsit** [comment] 2016-08-01 15:46
confirmed... ._.

**Comment by legoboy0215** [comment] 2016-08-02 01:43
Yeah. But IDK why some times it works.

**Comment by GlitchPlayer** [comment] 2016-08-02 09:08
Lel, I thought only template can be submitted?

**Comment by GlitchPlayer** [comment] 2016-08-02 09:08
Lmao

**Comment by ishitatsuyuki** [comment] 2016-08-02 12:33
@GlitchPlayer it doesn't matter if adequate information is provided. It looks better if unneeded things are trimmed down.

**Comment by Crypthu** [comment] 2016-08-13 09:27
EssentialsPE plugin funcions ... no bug

**Comment by Muqsit** [comment] 2016-08-13 14:08
@Crypthu That's because EssentialsPE doesn't send invisibility effect packet to the player.
---
And this seems to be a client bug.. ;-;

**Comment by robske110** [comment] 2016-08-22 17:42
Protocol change probably

**Comment by dktapps** [comment] 2016-08-24 14:34
This appears to be a client issue. I won't say "bug" because there aren't any circumstances that I know of that would require invisible particles in vanilla MCPE currently. Closing.

**Closed by dktapps** 2016-08-24 14:34 UTC
Labels: bug

**Comment by dktapps** [comment] 2016-10-24 18:26
This should be able to be fixed in the 0.16 update.

**Comment by Muqsit** [comment] 2016-12-17 18:26
This still hasn't been fixed.
