### ISSUE TITLE
Unpacking error

### ISSUE THREAD

**Issue by legoboy0215** [iTXTech/Genisys#996] opened 2016-05-20 12:52 UTC
#### Issue description
Unknown warning, possibly connected to the new UseItem update.

#### Steps to reproduce the issue
I am not really sure, sorry :( I'll keep testing.

#### OS and versions
<!--- Try Docker for library/extension issues
use the 'version' command in Genisys
This server is running Genisys 1.1dev-167baef "Ikaros" implementing API 2.0.0 for Minecraft: Pocket Edition v0.14.3 alpha (protocol version 70)
* Genisys: 1.1dev
* PHP: 7.0.2
* OS: Ubuntu

#### Crashdump, backtrace or other files
```
Warning: unpack(): Type n: not enough input, need 2, have 0 in phar:///root/pm/PocketMine-MP.phar/src/pocketmine/utils/Binary.php on line 274

and 

Warning: unpack(): Type V: not enough input, need 4, have 0 in phar:///root/pm/PocketMine-MP.phar/src/pocketmine/utils/Binary.php on line 343
Packet pocketmine\network\protocol\UseItemPacket 0x8eaa000003a900000041fffffec7023f7fc8003f70078000000000446b88e742853d71c39e2b3a010c0100001d000a00000a0700646973706c61790804004e616d650500576f6f64790000
TypeError: "Return value of pocketmine\item\Item::parseCompoundTag() must be an instance of pocketmine\nbt\tag\CompoundTag, instance of pocketmine\nbt\tag\ByteArrayTag returned" (EXCEPTION) in "/src/pocketmine/item/Item" at line 43
/src/pocketmine/item/Item(1693): pocketmine\item\Item->getNamedTag(boolean)
/src/pocketmine/Player(2716): pocketmine\item\Item->deepEquals(pocketmine\item\Item Item Unknown (29:2560)x0 tags:0x0700646973706c61790804004e616d650500576f6f64790000)
/src/pocketmine/network/RakLibInterface(139): pocketmine\Player->handleDataPacket(pocketmine\network\protocol\UseItemPacket object)
/src/raklib/server/ServerHandler(92): pocketmine\network\RakLibInterface->handleEncapsulated(string 201.68.129.47:19132, raklib\protocol\EncapsulatedPacket `.X................A.....?...?p......Dk..B.=q..+:.............display...Name..Woody.., integer 0)
/src/pocketmine/network/RakLibInterface(78): raklib\server\ServerHandler->handlePacket(boolean)
/src/pocketmine/network/Network(164): pocketmine\network\RakLibInterface->process(boolean)
/src/pocketmine/Server(2978): pocketmine\network\Network->processInterfaces(boolean)
/src/pocketmine/Server(2683): pocketmine\Server->tick(boolean)
/src/pocketmine/Server(2561): pocketmine\Server->tickProcessor(boolean)
/src/pocketmine/Server(2076): pocketmine\Server->start(boolean)
 /src/pocketmine/PocketMine(467): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///root/pm/PocketMine-MP.phar/, string /root/pm/, string /root/pm/plugins/, string unknown)
 (1): require_once(string phar:///root/pm/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

```

**Comment by gaoyichuan** [comment] 2016-05-20 12:58
While, a known issue ..

**Comment by legoboy0215** [comment] 2016-05-20 13:00
UseItemPacket? It suddenly happened to me.

**Comment by legoboy0215** [comment] 2016-05-20 13:00
It NEVER happened before to me.

**Comment by gaoyichuan** [comment] 2016-05-20 13:21
Yes, it's totally random and we can't find the cause..

**Comment by legoboy0215** [comment] 2016-05-20 13:27
I believe it's the new UseItemPacket update. These errors (Using debug level 2) directly says UseItemPacket. At least most of them do...

**Comment by gaoyichuan** [comment] 2016-05-20 14:03
But that issue existed long long ago..

**Comment by legoboy0215** [comment] 2016-05-20 14:12
Heres my idea: In rhe binary file, its all just functions like getSignedShort. But some of them are called from other places, in my case UseIemPacket. TBH, I bet I was quite lucky that an error with backyrace turned up…

**Comment by markkrueg** [comment] 2016-05-22 19:18
I don't have 100% confidence; but I am pretty sure this has been fixed in the newest source. I am running a current build with 50 players and no more "Warning: unpack(): Type n" right now. I've monitored for about an hour.

Since it's somewhat random and doesn't appear in the server.log file; it's a hard one to watch for.

**Closed** 2016-05-22 21:01 UTC

**Comment by legoboy0215** [comment] 2016-05-22 23:28
I solved it by stop using Anvil maps.
