### ISSUE TITLE
Iprotector protection not work Genisys_1.2dev-471

### ISSUE THREAD

**Issue by andris155** [iTXTech/Genisys#1186] opened 2016-06-16 20:41 UTC
#### Issue description

Not work Iprotector plugin protection.

#### Steps to reproduce the issue

Break, and place blocks, and hit players etc...

#### OS and versions

* Genisys: Genisys_1.2dev-471.phar
* PHP: 7.0.2 Linux x64
* OS: ubuntu

#### Crashdump, backtrace or other files
```
none
```

**Comment by dktapps** [comment] 2016-06-16 20:42
Duplicate of #1178

**Closed by dktapps** 2016-06-16 20:42 UTC
