### ISSUE TITLE
Inventory Block Bugs

### ISSUE THREAD

**Issue by Crypthu** [iTXTech/Genisys#1447] opened 2016-07-13 10:48 UTC
#### Issue description
it is a problem that sometimes even doubling the inventory Blocks!

#### OS and versions

* Genisys: 1.2dev
* PHP:7.0.8
* OS (server): Windows
* Game version: 0.15.x

#### Crashdump, backtrace, memory dumps, plugins list or other files
```
Paste here
```

**Comment by dktapps** [comment] 2016-07-13 10:50
Not enough information. 1.2dev could be any build.

**Comment by Crypthu** [comment] 2016-07-13 10:53
The trouble is that when I am creative For example, if you select a block can be deducted in addition to the dice have shown forth below

**Comment by dktapps** [comment] 2016-07-13 10:55
**1.2dev could be any build.** Provide proper version numbers or your issue cannot be resolved.

**Comment by dktapps** [comment] 2016-07-13 11:12
Closing due to not reproducible and lack of information.

**Closed by dktapps** 2016-07-13 11:12 UTC
