### ISSUE TITLE
No Cactus Damage - Win10 Users

### ISSUE THREAD

**Issue by ImagicalGamer** [iTXTech/Genisys#1195] opened 2016-06-17 15:06 UTC
#### Issue description
When standing next to a cactus (close enough to take damage) It acts like I'm taking damage (player flashes red etc) but I don't take ANY damage at all.

#### Steps to reproduce the issue
Use Win10 and stand next to a cactus

#### OS and versions
* Genisys: This server is running Genisys version 1.2dev-1e804e4 "Ikaros" (API 2.0.0)
* PHP: PHP7
* OS: Windows

#### Crashdump, backtrace or other files
```
Paste here
```

**Comment by dktapps** [comment] 2016-06-17 16:53
I can't reproduce this. Cacti kill me just fine.
![image](https://cloud.githubusercontent.com/assets/14214667/16158252/5b649b6a-34b4-11e6-9bc3-a6f4b06e9bcd.png)

**Comment by ishitatsuyuki** [comment] 2016-06-18 05:08
Closing. Reason: not reproducible.

**Closed by ishitatsuyuki** 2016-06-18 05:08 UTC
