### ISSUE TITLE
Setting An Items Damage is Broken

### ISSUE THREAD

**Issue by ImagicalGamer** [iTXTech/Genisys#1635] opened 2016-08-10 23:24 UTC
#### Issue description
When trying to set an items damage to 0 it doesn't work, the items damage doesn't change.

Plugin Code:
$item = $player->getInventory()->getItemInHand();
$item->setDamage(0);
$player->getInventory()->setItemInHand($item);

I'm on Win10 when this happens, I haven't trued on iOS or Android.

#### Steps to reproduce the issue
Try setting the damage of an item (that has already taken damage).

#### OS and versions
* Genisys: 69aef66b
* PHP: PHP7
* Server OS: Linux/Ubuntu
* Game version: 0.15.4/0.15.6

**Comment by ZedCee** [comment] 2016-08-11 05:40
`/give <player> <item[:damage]>` seems to set an items damage just fine.  So does a tool fixing command from a plugin i have.

Because the vanilla Genisys server does not have a command to repair already existing tools, I must assume that this is plugin related.  I recommend you contact the developer of the plugin, or contact one of our developers in the forums: gitter,im, Mattermost, or IRC.

**Comment by ishitatsuyuki** [comment] 2016-08-11 12:00
@ZedCee he's using w10 branch, reopening.

**Comment by dktapps** [comment] 2016-08-11 12:06
I'll look into it. Under what circumstances does this occur? In a plugin, with a comman, etc. ?

**Comment by ZedCee** [comment] 2016-08-11 14:35
Below is the gist of the /fixit command from [Grabbag](https://github.com/Muirfield/pocketmine-plugins) (The plugin I mentioned).  It fixes tools just fine.  May not be relevant, but for posterity's sake.
```
$item = clone $target->getInventory()->getItemInHand();
$item->setDamage(0);
$target->getInventory()->setItemInHand($item);
$target->getInventory()->sendContents($target);
```

**Comment by dktapps** [comment] 2016-08-11 14:37
@ZedCee also fine on Win10 branch, yes?

**Comment by ZedCee** [comment] 2016-08-11 14:38
Since it went up as a PR I am running it non-stop.  Forgive a test here or there.

**Comment by dktapps** [comment] 2016-08-11 14:39
Checking out the diff to see if I missed any parameter defaults. If I did that might be the problem.

**Comment by TheAppleGamer** [comment] 2016-08-11 14:47
Can confirm that on Windows 10 branch

**Comment by ZedCee** [comment] 2016-08-11 14:50
@ImagicalGamer It would really help us to know more details about how you produced this issue; A more detailed list of plugins used and steps taken would really expedite finding your problem.  
If you could please tell us more (update your ticket or post). Also note this for any future issue tickets.  Thank you.  
My apologies for closing the issue, the w10 branch is transitioning from unsupported to supported as we work toward a merge.

@TheAppleGamer  It is confirmed it is an issue on the w10 branch, could you also provide us with more details on how you reproduced this?

**Comment by TheAppleGamer** [comment] 2016-08-11 14:52
Well I am using a plugin that sends items on join. Well I set one of the items to 351:4 which is lapis, and when everyone would join they would get ink sacs. I can't reproduce it any other way @ZedCee

**Comment by ImagicalGamer** [comment] 2016-08-11 14:53
It's an plugin I created, Code:
`$item = $player->getInventory()->getItemInHand();
$item->setDamage(0);
$player->getInventory()->setItemInHand($item);`

I'm on Win10 when this happens, I haven't trued on iOS or Android.

**Comment by ZedCee** [comment] 2016-08-11 15:04
As it turns out there's enough fixes that the w10 branch plays well on iOS, so that's what I am using.  Thanks for getting back to us.  We're looking into it.

**Comment by ishitatsuyuki** [comment] 2016-08-11 15:08
Seems the difference is `sendContents()`, and should it be required?

**Comment by ImagicalGamer** [comment] 2016-08-11 15:16
@ishitatsuyuki Testing with `sendContents`, and @dktapps is right the item changes are typically sent.

**Comment by dktapps** [comment] 2016-08-11 15:18
I'll test this properly when I get home tonight. I can't understand why this would be problematic, but then plugin support wasn't my primary concern when this was in development. With the amount of API changes I made, it's hardly surprising things like this would happen.

**Comment by ImagicalGamer** [comment] 2016-08-11 15:20
@dktapps, @ishitatsuyuki It works when using `sendContents()` weird.

**Comment by dktapps** [comment] 2016-08-11 15:51
Unusual. Works for me the first time. Only the first time. Will investigate.

**Comment by dktapps** [comment] 2016-08-11 15:55
@ImagicalGamer Please try using `sendHeldItem` and report back.

**Comment by dktapps** [comment] 2016-08-11 17:55
I've pushed a commit to the Win10 branch that may fix the issue. Please try the latest build and report back.

**Comment by ImagicalGamer** [comment] 2016-08-11 21:34
@dktapps Works with latest commit!

**Comment by dktapps** [comment] 2016-08-12 12:06
Good good.

**Closed by dktapps** 2016-08-12 12:06 UTC
Labels: not confirmed, w10
