### ISSUE TITLE
Crash Dump

### ISSUE THREAD

**Issue by EmreTr1** [iTXTech/Genisys#1998] opened 2016-09-29 15:29 UTC
Genisys Crash Dump Thu Sep 29 22:57:08 CST 2016

Error: Return value of pocketmine\level\Level::getProvider() must implement interface pocketmine\level\format\LevelProvider, null returned
File: /src/pocketmine/level/Level
Line: 504
Type: notice

Code:
[495] 	 */
[496] 	public function getServer() : Server{
[497] 		return $this->server;
[498] 	}
[499] 
[500] 	/**
[501] 	 * @return LevelProvider
[502] 	 */
[503] 	final public function getProvider() : LevelProvider{
[504] 		return $this->provider;
[505] 	}
[506] 
[507] 	/**
[508] 	 * Returns the unique level identifier
[509] 	 *
[510] 	 * @return int
[511] 	 */
[512] 	final public function getId() : int{
[513] 		return $this->levelId;
[514] 	}

Backtrace:
#0 /src/pocketmine/Server(2684): pocketmine\Player->save(boolean 1)
#1 /src/pocketmine/Server(2869): pocketmine\Server->doAutoSave(boolean)
#2 /src/pocketmine/Server(2542): pocketmine\Server->tick(boolean)
#3 /src/pocketmine/Server(2420): pocketmine\Server->tickProcessor(boolean)
#4 /src/pocketmine/Server(2006): pocketmine\Server->start(boolean)
#5 /src/pocketmine/PocketMine(476): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string /storage/emulated/0/PocketMine/, string /storage/emulated/0/PocketMine/, string /storage/emulated/0/PocketMine/plugins/, string unknown)

Genisys version: 0000000000000000000000000000000000000000 [Protocol 83; API 2.0.0]
uname -a: Linux localhost 3.10.49-gacded96 #1 SMP PREEMPT Thu Apr 14 13:34:40 CST 2016 aarch64
PHP version: 7.0.9
Zend version: 3.0.0
OS : Linux, android

Server uptime: 5 minutes 9 seconds
Number of loaded worlds: 1
Players online: 1/20

Loaded plugins:
FolderPluginLoader 1.0.0 by  for API(s) 1.0.0
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
SignPortal 1.1.2 by 99leonchang for API(s) 1.3.1
iProtector 3.1b by LDX for API(s) 1.9.0, 2.0.0
Juices 0.5 by Ad5001 for API(s) 2.0.0
JukeboxPE 0.2.1 by GlitchPlayer & Others for API(s) 2.0.0
Slapper 1.2.9.7 by jojoe77777 for API(s) 2.0.0
MysU&GlxPet 1.0.4 by Adam1609&Justin //soul1st is support code not author for API(s) 2.0.0
EnderPearls 1.0.0 by XFuryMCPE for API(s) 1.12.0, 2.0.0
FakeServer 1.0.0 by Kairus Dark Seeker for API(s) 2.0.0
PmChair 1.2 by maru for API(s) 1.12.0, 1.13.0, 2.0.0
DevTools 1.1-iTX by PocketMine Team & iTX Technologies LLC for API(s) 2.0.0
SW_svile 0.6dev by svile for API(s) 2.0.0
joseper 1.0.0 by wolfdale for API(s) 2.0.0
MagicWE 0.1.13 by thebigsmileXD for API(s) 1.13.0, 2.0.0
MicroBattle 1.1 by EmreTr1 for API(s) 2.0.0
OneInTheQuiver 1 by SuperAdam47 for API(s) 2.0.0
BuildBattle 1 by EmreTr1 for API(s) 2.0.0
Runner 1 by EmreTr1 for API(s) 1.13.0
NPC 1.3.1 by onebone for API(s) 1.13.0, 2.0.0
TurfWars 0.5Beta by EmreTr1 for API(s) 2.0.0
MDCore beta1 by EmreTr1 for API(s) 2.0.0
WorldFixer 1 by CreeperFace for API(s) 1.12.0
VIP1b 2.0.0 by  for API(s) 2.0.0
MyZombie 2.9.0 by Zzm & boybook(Quit developing) for API(s) 1.0.0
WallWeapons 2.2 by Ragnok123 for API(s) 2.0.0
BedWars 1.dev by EmreTr1 for API(s) 1.13.1, 2.0.0

**Comment by dktapps** [comment] 2016-09-29 15:48
Duplicate of #1908

**Closed by dktapps** 2016-09-29 15:48 UTC
