### ISSUE TITLE
Paintings rotate when placed + wrong positioning

### ISSUE THREAD

**Issue by intagaming** [iTXTech/Genisys#1138] opened 2016-06-12 02:30 UTC
The search bar doesn't return any result for me with keyword "Painting" and there aren't any Painting issue open in the Issues section.

I just wonder if your Painting rotate work well? It ALWAYS rotate to be in the wall. See the attachment.

![untitled](https://cloud.githubusercontent.com/assets/16471365/15988576/182dbf80-3080-11e6-8962-9ff2b4caad65.png)

**Comment by Muqsit** [comment] 2016-06-12 05:23
Do the paintings rotate back to normal when you re login?

**Comment by intagaming** [comment] 2016-06-12 11:56
@Muqsit Hell yes sir how did u find out that ?

**Comment by ishitatsuyuki** [comment] 2016-06-12 11:57
Well, he may have known this problem already.

By the way, I don't like abbreviating too much since it's hard to read and impolite.

**Comment by intagaming** [comment] 2016-06-12 11:59
Okay i will improve that.
So are we have the solution yet ?

**Comment by ishitatsuyuki** [comment] 2016-06-12 12:03
Possibly no, and this sounds like easy to fix. I will investigate this.

**Comment by dktapps** [comment] 2016-06-18 14:26
Seems fixed as of 0.15.0. Closing.

**Comment by dktapps** [comment] 2016-06-18 14:30
Or not. Just doesn't happen as often. Strange

**Comment by PeratX** [comment] 2016-06-21 04:05
I don't catch this issue

**Comment by intagaming** [comment] 2016-06-21 04:30
My both MCPE & Minecraft Windows 10 Edition 0.15.0.1's painting still rotate.

**Comment by PeratX** [comment] 2016-06-27 00:04
0.15.1 never show this issue:/

**Comment by dktapps** [comment] 2016-06-27 08:17
Actually, I can reproduce this easily on my friend's server with latest updates to Genisys and MCPE both. It seems to be rather inconsistent though.

**Comment by PeratX** [comment] 2016-06-27 08:23
@dktapps How?

**Comment by dktapps** [comment] 2016-06-27 08:27
@PeratX It seems to vary from server to server. I have 2 or 3 test servers on various machines, and it happens very rarely on those, but my friend has one where it ALWAYS happens. Maybe something in the configuration?

**Comment by dktapps** [comment] 2016-06-27 08:40
@PeratX This is with 0.15.1.2 (Android)
![screenshot_2016-06-27-09-35-36](https://cloud.githubusercontent.com/assets/14214667/16373619/056bc212-3c4b-11e6-9365-37a0632f75f2.png)
![screenshot_2016-06-27-09-36-17](https://cloud.githubusercontent.com/assets/14214667/16373620/05701f4c-3c4b-11e6-9899-742bc7f2eb01.png)

**Comment by ZedCee** [comment] 2016-07-14 06:58
**Issue confirmed.**
Interestingly with the minor lag that occurs in placement of paintings:
- Briefly place correctly, then turn
- Always turn 90° to face left
- Can be restored with re-login(with sometimes interesting overlaps)
Hopefully that's useful

**OS and versions**
   - Genisys:  1.2dev-90c31fc
   - PHP: 7.0.6
   - Server OS: Linux
   - Client OS: iOS
   - Game version: 0.15.2

**Comment by TNT2000** [comment] 2016-07-19 01:38
.

**Comment by dschwartz783** [comment] 2016-07-21 10:48
The "briefly place correctly, then turn" thing is just a result of the client telling the server about the placement, after it already happens locally, for performance reasons. Genisys then somehow mishandles the placement and reports the painting placement to be 90° off. Strange...

**Comment by dschwartz783** [comment] 2016-07-21 11:32
Any idea why the paintings would be spawning on the wrong side of the block, but correcting themselves when you log out and in? That seems to be the entire problem.

**Comment by ZedCee** [comment] 2016-08-06 09:14
Still easily reproducible. 

**OS and versions**
   - Genisys:   dedb804
   - PHP: 7.0.9
   - Server OS: Linux
   - Client OS: iOS
   - Game version: 0.15.4

**Comment by dktapps** [comment] 2016-08-17 18:05
Working on this at the moment. Fixed rotation but having some positioning issues.

**Comment by dktapps** [comment] 2016-08-17 20:24
Fixed, please test at #1676

**Closed** 2016-08-18 05:18 UTC
Labels: bug
