### ISSUE TITLE
Enchant Table not work 0.16.0/0.16.1

### ISSUE THREAD

**Issue by andris155** [iTXTech/Genisys#2178] opened 2016-11-07 20:16 UTC
#### Issue description
Enchant Table not work. Not place enchant to tools.

#### Steps to reproduce the issue
Place tools in Enchant Table.

#### OS and versions

* Genisys: https://github.com/iTXTech/Genisys/tree/2e13c6d4645f5cffbcece4bccc55418d10d0320d
* PHP: 7.0.12 x64 Genisys script
* Server OS: Ubuntu 14.04.5 LTS
* Game version: 0.16.1/0.16.0

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
none
```

**Comment by dktapps** [comment] 2016-11-07 20:48
Duplicate of #2099

**Closed by dktapps** 2016-11-07 20:48 UTC
