### ISSUE TITLE
Server worlds and Genisys phar gets corrupted

### ISSUE THREAD

**Issue by Xelcronia** [iTXTech/Genisys#2291] opened 2016-12-22 13:35 UTC
#### Issue description

The server worlds and Genisys phar gets corrupted, I don't know for what reason. This, i believe started when I updated Genisys to version b49710e and has been getting corrupted ever since. I had to reinstall everything from scratch 6 to 7 times.

#### Steps to reproduce the issue

I don't know how exactly to reproduce this, it just does it at random

#### OS and versions

* Genisys: 6938a48
* PHP: 7.0.14
* Server OS: Ubuntu 15.10 64bit
* Game version: 0.16.2

#### Crashdump, backtrace, memory dumps, plugins list or other files

Before the files get corrupted and the server goes into an infinite crash loop, this error appeared
```
[Server thread/CRITICAL]: Error: "Cannot use object of type pocketmine\nbt\tag\EndTag as array" (EXCEPTION) in "/src/pocketmine/Player" 2016-12-22 [08:09:14] 

 --- Server reboots without warning ---

 [Server thread/WARNING]: SERVER IS RUNNING IN OFFLINE/INSECURE MODE! 
2016-12-22
 [08:09:14]  [Server thread/WARNING]: The server will make no attempt to authenticate usernames. Beware. 
2016-12-22 
```

After this, the files are corrupted and a lot of these errors on my worlds

```
 [Server thread/ERROR]: Could not load level "skyspawn": Invalid level.dat 
2016-12-22 [08:09:14]  [Server thread/CRITICAL]: pocketmine\utils\LevelException: "Invalid level.dat" (EXCEPTION) in "/src/pocketmine/level/format/generic/BaseLevelProvider" at line 55 
2016-12-22 [08:09:14]  [Server thread/EMERGENCY]: No default level has been loaded 
```

I couldn't get the error of the Corrupted Genisys phar because it didn't get recorded to the log. But it used to give an error about a ```Size Mismatch```

**Comment by poustmal** [comment] 2016-12-22 21:42
Try to delete the level.dat and make a world with the previous name you had.One time I have opened a world with clearsky and then with genisys,I had an error.idk

**Comment by Xelcronia** [comment] 2016-12-23 13:19
I've already tried that. After a few days, it gets corrupted again.

**Comment by dschwartz783** [comment] 2016-12-29 19:39
The EndTag can be used as the type of an empty List tag. That seems to be the source of this error.

**Comment by Xelcronia** [comment] 2017-01-01 10:08
@dschwartz783 Is there anything I can do about it?

**Comment by dschwartz783** [comment] 2017-01-01 18:07
I'm just guessing, but the problem is likely that somewhere in Player.php, there's a line of code which handles the Inventory list tag, which can sometimes be empty. When list tags are empty, the type of the items for that list can be that of the End tag. You could just edit the type if you know how to use a hex editor... It's not a complex format.

**Comment by JackNoordhuis** [comment] 2017-01-09 22:27
@dschwartz783 Player.php doesn't have anything to do with any level.dat files.

@Xelcronia The source of this error seems to be a corrupted world; this has nothing to do with Genisys itself, so I'll close this issue for now. If you can reproduce this with another world feel free to re-open the issue :)

**Closed by JackNoordhuis** 2017-01-09 22:27 UTC

**Comment by dschwartz783** [comment] 2017-01-10 04:42
@JackNoordhuis That doesn't sound like a dev talking, to be honest. Player.php uses NBT tags, the same NBT tags that level.dat uses, which means that the two could, in fact, be related. When it comes to debugging software, never rule anything out. I'd like more data on this issue before dismissing it.

**Comment by JackNoordhuis** [comment] 2017-01-10 05:10
@dschwartz783 The player class has nothing to do with this issue, you mentioned the end tag and player inventories which are saved into completely seperate files and loaded in their respective classes. The error @Xelcronia provided in the issue description says it all, it's a level corruption issue. This issue is NBT related but hasn't got the slightest relation to player inventories in PocketMine, they may both be saved in NBT but a developer such as yourself should know data doesn't decide to randomly move to another file by itself. If you want this to be investigated further feel free to do so, I've got no interest in doing so and clearly all the other contributors don't either. Just keep in mind this is the only time an issue like this has been reported in all the years PocketMine has been around so it either isn't very common or is a result of data corruption.

**Comment by dschwartz783** [comment] 2017-01-10 05:38
The non-lazy approach would be to request more data from the person who opened this issue, maybe a copy of his worlds. I'm at least trying to think of what might be going wrong. Closing it solves nothing. This issue may resurface in the future.

**Comment by Xelcronia** [comment] 2017-01-10 05:41
It wasn't one world that got corrupted, all my worlds and the Genisys phar.

**Comment by dschwartz783** [comment] 2017-01-10 05:42
Also, it's worth noting that the original crash is the result of something in Player, which is possibly the cause of this, hence my reference to Player.php earlier.

**Comment by dschwartz783** [comment] 2017-01-10 05:42
Right, so it is probably genisys doing the corruption.

**Comment by dschwartz783** [comment] 2017-01-10 05:43
Reopen this issue

**Comment by Xelcronia** [comment] 2017-01-10 05:45
I'd like to leave this here. Because everything is being re-written and I don't use those worlds anymore. I'll open this if the same occurs again. Thanks for the help! @dschwartz783 @JackNoordhuis
