### ISSUE TITLE
player->teleport() causes complete server freezes

### ISSUE THREAD

**Issue by DaMatrix** [iTXTech/Genisys#1889] opened 2016-09-07 16:15 UTC
#### Issue description

Whenever (or most times) when `Player->teleport();` is called (for instance in /tp or HereAuth location hider) the server goes into a strange state where it completely freezes up (players are not disconnected but do not recieve any more packets, new players cannot join, the log does not print anything and commands in the console do not send any message, window title stops updating, etc.) and cannot be stopped by any means exept `sudo reboot` (no, `sudo kill <PID>` does not even work).  There is nothing put in `crashdumps`, so no info on this other than what happens.  This has been a problem since the latest official release came out (any maybe even earlier, my server was created on 0.15).  Any help is appreciated.
#### Steps to reproduce the issue

Install any plugin that uses player->teleport(blah); and use the teleport function a few times, or /tp a few times
#### OS and versions

- Genisys:  
  This server is running Genisys (codename "Kyrios") API: 2.0.0 (iTX API version 1.9.1)
  (aka latest source from github)
  (aka commit f44afc854de480f842c2e702bd237b9ba473e07c)
- PHP: 7.0.3
- Server OS: Ubuntu server 16.04
- Game version: 0.15.4
#### Crashdump, backtrace, memory dumps, plugins list or other files

Nothing, the server doesn't output anything

**Comment by Leo3418** [comment] 2016-09-08 03:10
To force stop Genisys process, you may use `kill -9 <PID>`.

**Comment by DaMatrix** [comment] 2016-09-08 04:30
Ok, thanks :D


Sent from my Samsung device

-------- Original message --------

**Comment by DaMatrix** [comment] 2016-09-08 16:57
nope, it just happened again and that didn't help it.

**Comment by EpicSteve33** [comment] 2016-09-09 17:13
@DaMatrix if you are trying to teleport players to an xyz I'd recommend using something like this 

`Player->teleport(new Vector3(0, 0, 0));` 

or if you are teleporting to another world 

`Player->teleport(Server::getInstance()->getLevelByName("world")->getSafeSpawn()); `

If your server still freezes I'd recommend updating genisys or do a fresh installing of genisys on your machine also delete the players folder if that doesn't help

**Comment by DaMatrix** [comment] 2016-09-09 18:28
It's not really a problem any more, I managed to sidestep it by setting up Nemisys and having auth on one server and the actual server on the other.  I set the server up to automatically clone the github repo every time a new commit is made, so that wouldn't be the problem. I think that this issue is as good as resolved, so I will close it.

-------- Original message --------

**Comment by legoboy0215** [comment] 2016-09-10 00:27
Wow... This is was an issue for me. I managed to fix it by adding 
`$level->loadChunk($x >> 4, $z >> 4);`

**Comment by DaMatrix** [comment] 2016-09-10 05:28
Ok,thanks!  I added it directly before `return true`.  Is that correct?

**Comment by DaMatrix** [comment] 2016-09-10 07:22
Seems to have fixed itself, closing

**Comment by legoboy0215** [comment] 2016-09-15 04:48
Still in for me. I get freezes a lot because of multi-world teleportation.

**Comment by DaMatrix** [comment] 2016-09-15 05:04
Do you have pureentities on your server? Removing it fixed it for me.

**Comment by legoboy0215** [comment] 2016-09-15 07:23
PureEntities??? No. I have a custom minigame plugin that simply teleports the player to the match world. When they teleport, the server freezes.

**Comment by dktapps** [comment] 2016-09-15 10:55
I'm unable to reproduce this. Can you provide any further detail?

**Comment by legoboy0215** [comment] 2016-09-15 23:55
Hm... Not any more I'm afraid. Somehow, loading the chunk first temporarily fixed the issue, but it came back again.

**Comment by Muqsit** [comment] 2016-09-19 18:28
kill -9 <PID> works.

**Comment by Muqsit** [comment] 2016-09-19 18:29
`kill -9 <PID>` works.

**Comment by dktapps** [comment] 2016-09-19 18:33
@Muqsit https://github.com/iTXTech/Genisys/issues/1889#issuecomment-245481782 ... :P

**Comment by Muqsit** [comment] 2016-09-19 19:05
Is this related to too many chunks loading (if you have multiple worlds)? This might also occur if you have assorted worlds (assorted in format. Eg: world1 is anvil, world2 is mcregion, world3 is anvil...) + you are trying to load too many chunks.

**Comment by DaMatrix** [comment] 2016-09-19 20:23
Honestly I have no idea. I can't seem to be able to reproduce it anymore, although it still seems to happen occasionally. I'm going to leave this open, but with the extreme lack of information it's almost impossible to get this fixed.

**Comment by Muqsit** [comment] 2016-09-20 03:29
Sounds good. To people who can reproduce this issue, please send the system load percentage.

**Comment by legoboy0215** [comment] 2016-10-10 01:09
@Muqsit 102%.

https://timings.aikar.co/?url=23301127

I added a line of code that runs /timings paste right after the teleport. It does teleport, but it freezes for about 5 minutes after that. I am running a minigame, SkyWars. When I removed the code that sets a lot of blocks for the glass cage, it didn't freeze the server AT ALL. Certainly something to do with setBlock, imo.

Also, the timings show receive packet interact packet is taking a long time. No idea why too...

**Comment by DaMatrix** [comment] 2016-10-10 07:44
maybe it's caused by /setblock in a chunk that hasn't been loaded yet? i did notice this while trying to make a fix for nether portals, i ended up adding a 30 second delay between the player being teleported and the blocks being set because the server just froze otherwise.

**Comment by dktapps** [comment] 2016-10-10 08:54
Will investigate. You know how it goes - we can only fix it once we can reproduce it. Thanks guys.

**Comment by Misteboss** [comment] 2016-10-16 12:53
I think it's in rapport with chunk loading

**Comment by dktapps** [comment] 2016-11-03 10:24
Should be fixed as of #2137 , will close this. If the issue still occurs, please do let us know.

**Comment by DaMatrix** [comment] 2016-11-03 10:27
ok, thanks! :D

**Comment by legoboy0215** [comment] 2016-11-06 03:19
OMG thanks

**Comment by legoboy0215** [comment] 2016-11-25 04:18
Please reopen this. It still happens to me, using the latest build on GitLab.

**Comment by legoboy0215** [comment] 2016-11-25 04:41
I really can't provide any more information, I apologize.

**Comment by dktapps** [comment] 2017-01-05 21:48
Would it be correct enough to say that this bug has been occurring since 21 August 2016?

**Comment by DaMatrix** [comment] 2017-01-06 05:20
Would agree with that, so long as @legoboy0215 is still getting it. I haven't been able to reproduce it for a while

**Comment by legoboy0215** [comment] 2017-01-06 08:09
Hello. I have not been able to reproduce this anymore, since I used PMMP. It still happens on Genisys, afaik.

**Comment by dktapps** [comment] 2017-01-06 10:30
https://github.com/iTXTech/Genisys/commit/b9e93d696cbf3e37339cd67bc1c46404ce47e2c3

(somehow the commit message did not reference this issue, even though I clearly typed it >_<)

**Closed by dktapps** 2017-01-06 10:30 UTC
Labels: investigation needed
