### ISSUE TITLE
Half-trees on chunk boundaries

### ISSUE THREAD

**Issue by ara2am** [iTXTech/Genisys#1611] opened 2016-08-06 08:11 UTC
- Genisys: 477c6b2
- PHP: 7
- Server OS: Windows 7
- Game version: 0.15.4.0

Hello all. Sometimes i can see bugs with trees, which are located at the intersection of chunks.
Some part of this trees is cut out, but when i reconnect to server the trees recovering and i can see it without this bug. 
When i see bug:
![studio_20160806_110023](https://cloud.githubusercontent.com/assets/12220551/17455616/47727b2a-5bc6-11e6-8946-91f15f539e84.jpg)
When i reconnect to server:
![studio_20160806_110912](https://cloud.githubusercontent.com/assets/12220551/17455621/7afc7388-5bc6-11e6-8ee1-0cb4cded513e.png)

**Comment by ZedCee** [comment] 2016-08-06 09:03
The server connection with MCPE is made via udp connection, which lacks a three-way handshake, and can have occasional packet loss.   
Meaning some information may not make it to the client.    This is an online gaming and streaming data standard.

I'll leave this open for now and perhaps one of the devs can share another theory.

**Comment by dktapps** [comment] 2016-08-06 09:59
I can confirm this bug., yes. It's been around for a veeeeeeeeery long time.

**Comment by dktapps** [comment] 2016-08-06 10:31
Actually, I think I know _exactly_ what's causing this bug. This... may be a challenge to fix.

**Comment by gaoyichuan** [comment] 2016-08-06 22:08
Yep, it's a very very old bug of PM....

**Comment by PeratX** [comment] 2016-08-07 00:59
This can not be fixed in a short time. Also appears in single play.

**Comment by mixailenko5** [comment] 2016-08-07 07:52
@PeratX i will be try to fix it. If i find the bug i send issue to this gitHub, because  i haven't a lot of time to fix them.

**Comment by dschwartz783** [comment] 2016-08-10 23:31
@ZedCee incorrect. It is correct that UDP behaves this way, but RakNet allows the connection to work like TCP, UDP, or a variety of other in-between levels, with varying amounts of reliability. If this truly is a problem with packet loss, then we need to use a different reliability level.

**Comment by dktapps** [comment] 2016-08-11 18:01
I believe this is to do with chunk generation. If a tree generates on the edge of a new chunk and the leaves overlap into an already-generated chunk, the updated blocks in the existing chunk are not sent to the client. The client will only be able to see the parts of the tree in the new chunk. Resending the chunks would probably fix this issue, but there's probably a cleaner way to do it than sending the entire chunk for a few leaves.

**Comment by thebigsmileXD** [comment] 2016-09-13 06:02
@dktapps true. is it possible to clear the chunk cache and setchanged on the chunk when this happens?

**Comment by dschwartz783** [comment] 2016-09-13 16:53
Probably the solution is to calculate the surrounding chunks, before generating terrain, and sending it to the client.

**Comment by dktapps** [comment] 2017-02-05 14:45
Closing this in favour of pmmp/PocketMine-MP#265. If anyone would like to test pmmp/PocketMine-MP#328, please leave comments there. The change will be cherry-picked to Genisys after appropriate testing and QA has been done.

**Closed by dktapps** 2017-02-05 14:45 UTC
Labels: bug
