### ISSUE TITLE
LevelProvider null returned

### ISSUE THREAD

**Issue by yhzx233** [iTXTech/Genisys#1908] opened 2016-09-09 12:39 UTC
#### Issue description

有时服务器突然报错接着崩溃，希望尽快修复

#### Steps to reproduce the issue

具体如何崩溃我也不是很清楚

#### OS and versions

- Genisys:Kyrios
- PHP:7.0.10
- Server OS:Centos7.0
- Game version: 0.15.x
#### Crashdump, backtrace, memory dumps, plugins list or other files

```
Error: Return value of pocketmine\level\Level::getProvider() must implement interface pocketmine\level\format\LevelProvider, null returned
File: /src/pocketmine/level/Level
Line: 504
Type: notice

Code:
[495]    */
[496]   public function getServer() : Server{
[497]       return $this->server;
[498]   }
[499] 
[500]   /**
[501]    * @return LevelProvider
[502]    */
[503]   final public function getProvider() : LevelProvider{
[504]       return $this->provider;
[505]   }
[506] 
[507]   /**
[508]    * Returns the unique level identifier
[509]    *
[510]    * @return int
[511]    */
[512]   final public function getId() : int{
[513]       return $this->levelId;
[514]   }

Backtrace:
#0 /src/pocketmine/Server(2713): pocketmine\Player->save(boolean 1)
#1 /src/pocketmine/Server(2898): pocketmine\Server->doAutoSave(boolean)
#2 /src/pocketmine/Server(2571): pocketmine\Server->tick(boolean)
#3 /src/pocketmine/Server(2449): pocketmine\Server->tickProcessor(boolean)
#4 /src/pocketmine/Server(2035): pocketmine\Server->start(boolean)
#5 /src/pocketmine/PocketMine(467): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///home/games/Genisys_Kyrios_82f9e7f.phar/, string /home/games/, string /home/games/plugins/, string unknown)
#6 (1): require_once(string phar:///home/games/Genisys_Kyrios_82f9e7f.phar/src/pocketmine/PocketMine.php)

Genisys version: 0000000000000000000000000000000000000000 [Protocol 82; API 2.0.0]
uname -a: Linux ebs-39120 3.10.0-123.el7.x86_64 #1 SMP Mon Jun 30 12:09:22 UTC 2014 x86_64
PHP version: 7.0.10
Zend version: 3.0.0
OS : Linux, linux

Server uptime: 25 分 1 秒
Number of loaded worlds: 3
Players online: 5/100

Loaded plugins:
ZXDAKernel 5.1.2.5 by FENGberd for API(s) 1.0.0, 2.0.0, 3.0.0, 4.0.0, 5.0.0, 6.0.0, 7.0.0, 8.0.0, 9.0.0
Bedwars 2.3 by Bluplayz for API(s) 1.14.0, 2.0.0
GGame 1.0.0 by Yhzx for API(s) 2.0.0
Protection 2.6.7 by zzx for API(s) 1.0.0, 2.0.0
```

**Comment by dktapps** [comment] 2016-09-09 13:17
@legoboy0215 is this the same as the problem you had a while back?

**Comment by MrKiaN** [comment] 2016-09-09 13:18
Are This Sv Support For 0.15.6 Or  0.15.7

**Comment by legoboy0215** [comment] 2016-09-10 00:16
Yeah, @dktapps. Can't reproduce it now though. BTW, you have such a good memory XD

**Comment by legoboy0215** [comment] 2016-09-10 00:18
@yhzx233 Probably a plugin issue. On the first look, it is probably GGame or BedWars.

**Comment by dktapps** [comment] 2016-09-10 00:21
Referencing https://github.com/PocketMine/PocketMine-MP/pull/4205 for testing at a later date.

**Comment by legoboy0215** [comment] 2016-09-10 00:23
@dktapps Should I open another issue for that? I am having that getName on null occasionally now.

**Comment by dktapps** [comment] 2016-09-10 00:28
@legoboy0215 I believe it's the same problem causing different results.

**Comment by legoboy0215** [comment] 2016-09-14 11:16
@dktapps Finally, another evidence.

```
Genisys Crash Dump Wed Sep 14 04:12:49 PDT 2016

Error: Call to a member function getName() on null
File: /src/pocketmine/level/Level
Line: 3021
Type: notice

Code:
[3012] 		return (int) $this->time;
[3013] 	}
[3014] 
[3015] 	/**
[3016] 	 * Returns the Level name
[3017] 	 *
[3018] 	 * @return string
[3019] 	 */
[3020] 	public function getName() : string{
[3021] 		return $this->provider->getName();
[3022] 	}
[3023] 
[3024] 	/**
[3025] 	 * Returns the Level folder name
[3026] 	 *
[3027] 	 * @return string
[3028] 	 */
[3029] 	public function getFolderName(){
[3030] 		return $this->folderName;
[3031] 	}

Backtrace:
#0 /src/pocketmine/Server(2981): pocketmine\Server->checkTickUpdates(integer 9994, double 1473851569.5278)
#1 /src/pocketmine/Server(2676): pocketmine\Server->tick(boolean)
#2 /src/pocketmine/Server(2554): pocketmine\Server->tickProcessor(boolean)
#3 /src/pocketmine/Server(2119): pocketmine\Server->start(boolean)
#4 /src/pocketmine/PocketMine(467): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///home/minecraft/multicraft/jar/genisys.phar/, string /home/minecraft/multicraft/servers/server4066/, string /home/minecraft/multicraft/servers/server4066/plugins/, string unknown)
#5 (1): require_once(string phar:///home/minecraft/multicraft/jar/genisys.phar/src/pocketmine/PocketMine.php)

Genisys version: 0000000000000000000000000000000000000000 [Protocol 82; API 2.0.0]
uname -a: Linux lamcpe2 2.6.32-042stab113.11 #1 SMP Fri Dec 18 17:32:04 MSK 2015 x86_64
PHP version: 7.0.8
Zend version: 3.0.0
OS : Linux, linux

Server uptime: 8 minutes 21 seconds
Number of loaded worlds: 15
Players online: 32/150

Loaded plugins:
AlwaysSpawn 2.2.2 by Philip Shilling for API(s) 1.12.0
iProtector 3.1b by LDX for API(s) 1.9.0, 2.0.0
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
NoAdvertisingPE 1.0.1 by Vaivez66 for API(s) 1.12.0
CustomAlerts 1.6b by EvolSoft for API(s) 2.0.0
HelpModifier 1.0.0 by applqpak for API(s) 1.0.0, 2.0.0
BlockCmdPE 1.0.1 by Vaivez66 for API(s) 1.12.0, 2.0.0
AntiSpam 1.3 by xBeastMode for API(s) 2.0.0
EconomyShop 2.0.7 by onebone for API(s) 1.12.0
WorldGM 1.1.0 by Vaivez66 for API(s) 1.12.0, 2.0.0
ManyWorlds 2.1.0 by aliuly for API(s) 2.0.0
VoteReward 3.0.2 by LDX for API(s) 1.12.0, 2.0.0
PvPWorlds 1 by  for API(s) 1.0.0
ColorMatch 1.1.2 by CreeperFace for API(s) 1.12.0
ServerAuth 2.13 by EvolSoft for API(s) 1.11.0
Slapper 1.2.9.5 by jojoe77777 for API(s) 2.0.0
Broadcaster 1.16 by EvolSoft for API(s) 1.12.0
PurePerms 1.3.7 by 64FF00 & ProjectInfinity for API(s) 1.13.0, 2.0.0
MSpawns 1.5 by EvolSoft for API(s) 1.11.0
CrateKeys 1.0.5 by CDFalcon, CDFalcon for API(s) 1.13.0
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
BanItem 2.2 by LDX for API(s) 1.0.0, 2.0.0
BrickBattle 1.0.0 by Legoboy for API(s) 2.0.0
EconomySell 2.0.7 by onebone for API(s) 1.12.0
SimpleWarp 2.1.0 by Falkirks for API(s) 1.12.0
PureChat 1.4.0 by 64FF00 for API(s) 1.13.0, 2.0.0
MyPlot 1 by Wies and Exxarion for API(s) 1.0.0
```
The getName is called on $this->provider, which is probably the LevelProvider.

**Comment by legoboy0215** [comment] 2016-09-14 11:16
This happened when I unloaded and loaded the world.

**Comment by legoboy0215** [comment] 2016-09-14 11:20
Don't want to upset you with my noobishness, but this is the only place _I_ see could possibly cause this error. https://github.com/iTXTech/Genisys/blob/eb168db2e3a32097ba3d654bbcafc3e7d113efa8/src/pocketmine/level/Level.php#L528-L529

It fits since I did unload the level. Perhaps while unloading, the getName is called right before the level closed?

**Comment by dktapps** [comment] 2016-09-14 11:22
That's very strange. When a world is unloaded, the world itself should not even be accessible anymore I would say. The Level instance should be destroyed IMO.

**Comment by dktapps** [comment] 2016-09-14 11:29
@legoboy0215 how are you unloading the level? Plugin/code snippet?

**Comment by legoboy0215** [comment] 2016-09-14 11:32
```
	public function unload(){
        $level = $this->base->getServer()->getLevelByName('test');
        $lobby = $this->base->getServer()->getDefaultLevel();
        foreach($level->getPlayers() as $p){ 
            $p->teleport($lobby->getSpawnLocation());
            $p->setLevel($lobby);
        } //TODO: Remove getName on null issue #1 hack
        return $this->base->getServer()->unloadLevel($level);
    }

    public function load(){
        $this->base->getServer()->loadLevel('test');
        $level = $this->base->getServer()->getLevelByName('test');
        $level->setAutoSave(false);
    }
	
	$this->unload();
	$this->load();
```

**Comment by dktapps** [comment] 2016-09-15 13:43
I discovered a memory leak which relates to this issue. (^_^)

**Comment by dktapps** [comment] 2016-09-15 13:49
References (including incomplete or improperly formatted tickets):
#1813 , #1465 , #1126

**Comment by yhzx233** [comment] 2016-09-24 01:36
我想问题也许出在 : LevelProvider

**Comment by yhzx233** [comment] 2016-10-02 13:16
将/src/pocketmine/level/Level.php503行的 : LevelProvider去掉即可修复此问题！！

**Comment by dktapps** [comment] 2016-10-02 13:24
@yhzx233 that won't fix the problem, only mitigate it.

**Comment by yhzx233** [comment] 2016-10-02 13:28
@dktapps Genisy的一次更新导致了这个问题，因为加入了 : LevelProvider导致崩溃，所以现在你可以先把它去掉吗？

**Comment by dktapps** [comment] 2016-10-02 14:29
@yhzx233 I could do that, but as I said, that doesn't fix the actual problem. LevelProvider should never be null to begin with. This simply highlights a more deep-rooted bug.

**Comment by Misteboss** [comment] 2016-10-25 20:59
Me too the bug happen when i load or unload a world :/

**Comment by dktapps** [comment] 2016-10-30 20:10
Would anybody like to try https://github.com/pmmp/PocketMine-MP/commit/87ba3264cfdce5c4c6d08bac6b9400e7d082b36e ?

**Closed** 2016-11-09 14:29 UTC
Labels: bug
